import { HealthCondition } from './types';

export const healthConditions: HealthCondition[] = [
  {
    id: 'diabetes-type2',
    name: 'Type 2 Diabetes',
    description: 'A chronic condition affecting the way the body processes blood sugar (glucose).',
    foodsToEat: [
      'Leafy greens (spinach, kale)',
      'Fatty fish (salmon, mackerel)',
      'Whole grains (oats, quinoa)',
      'Legumes (lentils, chickpeas)',
      'Nuts (almonds, walnuts)',
      'Berries (blueberries, strawberries)',
      'Sweet potatoes',
      'Greek yogurt',
    ],
    foodsToAvoid: [
      'Sugary drinks and sodas',
      'White bread and refined grains',
      'Pastries and baked goods',
      'Fried foods',
      'Processed meats',
      'Sweetened cereals',
      'Candy and chocolate',
      'Fruit juices with added sugar',
    ],
    exercises: [
      'Brisk walking (30 min/day)',
      'Swimming',
      'Cycling',
      'Strength training (2-3x/week)',
      'Yoga',
    ],
    lifestyle: [
      'Monitor blood sugar regularly',
      'Maintain consistent meal times',
      'Control portion sizes',
      'Stay hydrated',
      'Get 7-8 hours of sleep',
      'Manage stress levels',
    ],
    source: 'American Diabetes Association',
  },
  {
    id: 'hypertension',
    name: 'Hypertension (High Blood Pressure)',
    description: 'A condition where the force of blood against artery walls is consistently too high.',
    foodsToEat: [
      'Leafy greens',
      'Berries',
      'Beets',
      'Oats',
      'Bananas',
      'Fatty fish',
      'Garlic',
      'Olive oil',
    ],
    foodsToAvoid: [
      'High-sodium foods',
      'Processed and canned foods',
      'Deli meats',
      'Pickled foods',
      'Soy sauce',
      'Alcohol',
      'Caffeine (excess)',
      'Fried foods',
    ],
    exercises: [
      'Walking (30 min/day)',
      'Swimming',
      'Cycling',
      'Yoga',
      'Tai chi',
    ],
    lifestyle: [
      'Reduce sodium intake to <2300mg/day',
      'Monitor blood pressure regularly',
      'Maintain healthy weight',
      'Limit alcohol consumption',
      'Manage stress',
      'Quit smoking',
    ],
    source: 'American Heart Association',
  },
  {
    id: 'cholesterol-high',
    name: 'High Cholesterol',
    description: 'Elevated levels of cholesterol in the blood, increasing heart disease risk.',
    foodsToEat: [
      'Oats and barley',
      'Fatty fish',
      'Nuts and seeds',
      'Olive oil',
      'Beans and lentils',
      'Fruits (apples, grapes)',
      'Vegetables',
      'Whole grains',
    ],
    foodsToAvoid: [
      'Red meat (excess)',
      'Full-fat dairy',
      'Fried foods',
      'Processed baked goods',
      'Trans fats',
      'Coconut oil and palm oil',
      'Shellfish (excess)',
      'Organ meats',
    ],
    exercises: [
      'Aerobic exercise (30 min/day)',
      'Walking',
      'Jogging',
      'Cycling',
      'Swimming',
    ],
    lifestyle: [
      'Maintain healthy weight',
      'Quit smoking',
      'Limit alcohol',
      'Eat fiber-rich foods',
      'Reduce saturated fats',
      'Regular check-ups',
    ],
    source: 'Mayo Clinic',
  },
  {
    id: 'obesity',
    name: 'Obesity',
    description: 'A medical condition involving excessive body fat that increases health risks.',
    foodsToEat: [
      'Lean proteins (chicken, fish, tofu)',
      'Vegetables (all types)',
      'Fruits (moderate portions)',
      'Whole grains',
      'Legumes',
      'Low-fat dairy',
      'Nuts (small portions)',
      'Water and herbal teas',
    ],
    foodsToAvoid: [
      'Sugary beverages',
      'Fast food',
      'Processed snacks',
      'White bread and pasta',
      'Candy and sweets',
      'Fried foods',
      'Alcohol',
      'Large portion sizes',
    ],
    exercises: [
      'Walking (gradually increase to 60 min)',
      'Swimming',
      'Cycling',
      'Strength training',
      'Group fitness classes',
    ],
    lifestyle: [
      'Set realistic weight loss goals',
      'Track food intake',
      'Eat slowly and mindfully',
      'Get adequate sleep',
      'Find accountability partner',
      'Celebrate small victories',
    ],
    source: 'WHO',
  },
  {
    id: 'pcos',
    name: 'PCOS (Polycystic Ovary Syndrome)',
    description: 'A hormonal disorder common among women of reproductive age.',
    foodsToEat: [
      'Anti-inflammatory foods',
      'Fatty fish',
      'Leafy greens',
      'Berries',
      'Nuts and seeds',
      'Whole grains',
      'Lean proteins',
      'Legumes',
    ],
    foodsToAvoid: [
      'Refined carbohydrates',
      'Sugary foods',
      'Processed foods',
      'Red meat (excess)',
      'Soy products (excess)',
      'Caffeine (excess)',
      'Alcohol',
      'Trans fats',
    ],
    exercises: [
      'Strength training (3x/week)',
      'Walking',
      'Yoga',
      'HIIT (moderate)',
      'Swimming',
    ],
    lifestyle: [
      'Manage stress',
      'Prioritize sleep',
      'Maintain healthy weight',
      'Track menstrual cycle',
      'Limit processed foods',
      'Consider anti-inflammatory diet',
    ],
    source: 'PCOS Awareness Association',
  },
  {
    id: 'back-pain',
    name: 'Chronic Back Pain',
    description: 'Persistent pain in the back that can affect daily activities.',
    foodsToEat: [
      'Anti-inflammatory foods',
      'Fatty fish (omega-3s)',
      'Leafy greens',
      'Berries',
      'Nuts',
      'Turmeric',
      'Ginger',
      'Green tea',
    ],
    foodsToAvoid: [
      'Processed foods',
      'Sugary foods',
      'Fried foods',
      'Excess alcohol',
      'Red meat (excess)',
      'Refined grains',
      'Dairy (if inflammatory)',
      'Caffeine (excess)',
    ],
    exercises: [
      'Swimming',
      'Walking',
      'Yoga',
      'Pilates',
      'Core strengthening',
      'Stretching',
    ],
    lifestyle: [
      'Maintain good posture',
      'Use ergonomic furniture',
      'Take regular breaks from sitting',
      'Apply heat/cold therapy',
      'Manage stress',
      'Get adequate sleep',
    ],
    source: 'Mayo Clinic',
  },
  {
    id: 'thyroid-hypothyroid',
    name: 'Hypothyroidism',
    description: 'A condition where the thyroid gland doesn\'t produce enough hormones.',
    foodsToEat: [
      'Iodine-rich foods (seaweed, fish)',
      'Selenium-rich foods (Brazil nuts)',
      'Zinc-rich foods (pumpkin seeds)',
      'Fruits and vegetables',
      'Whole grains',
      'Lean proteins',
      'Legumes',
      'Dairy',
    ],
    foodsToAvoid: [
      'Soy products (excess)',
      'Cruciferous vegetables (raw, excess)',
      'Processed foods',
      'High-sugar foods',
      'Fried foods',
      'Alcohol',
      'Caffeine (excess)',
      'Refined grains',
    ],
    exercises: [
      'Walking',
      'Swimming',
      'Yoga',
      'Strength training',
      'Cycling',
    ],
    lifestyle: [
      'Take medication as prescribed',
      'Get regular thyroid tests',
      'Manage stress',
      'Get adequate sleep',
      'Maintain healthy weight',
      'Eat regular meals',
    ],
    source: 'American Thyroid Association',
  },
  {
    id: 'ibs',
    name: 'IBS (Irritable Bowel Syndrome)',
    description: 'A common disorder affecting the large intestine.',
    foodsToEat: [
      'Low-FODMAP foods',
      'Bananas',
      'Blueberries',
      'Carrots',
      'Grapes',
      'Oats',
      'Rice',
      'Lean proteins',
    ],
    foodsToAvoid: [
      'High-FODMAP foods',
      'Beans and lentils',
      'Onions and garlic',
      'Dairy (if lactose intolerant)',
      'Wheat products',
      'Carbonated drinks',
      'Alcohol',
      'Caffeine',
    ],
    exercises: [
      'Walking',
      'Yoga',
      'Swimming',
      'Cycling',
      'Gentle stretching',
    ],
    lifestyle: [
      'Eat at regular times',
      'Manage stress',
      'Get adequate sleep',
      'Keep a food diary',
      'Eat slowly',
      'Stay hydrated',
    ],
    source: 'IBS Network',
  },
  {
    id: 'asthma',
    name: 'Asthma',
    description: 'A condition affecting the airways that carry air to and from the lungs.',
    foodsToEat: [
      'Fruits (apples, bananas)',
      'Vegetables',
      'Fatty fish',
      'Nuts',
      'Seeds',
      'Whole grains',
      'Lean proteins',
      'Ginger',
    ],
    foodsToAvoid: [
      'Sulfite-containing foods',
      'Preserved foods',
      'Shellfish',
      'Artificial sweeteners',
      'Gas-producing foods',
      'Cold drinks',
      'Excess dairy (if sensitive)',
      'Fried foods',
    ],
    exercises: [
      'Swimming (warm, humid environments)',
      'Walking',
      'Yoga',
      'Cycling',
      'Pilates',
    ],
    lifestyle: [
      'Avoid known triggers',
      'Use inhaler as prescribed',
      'Monitor peak flow',
      'Keep home clean',
      'Manage allergies',
      'Get flu vaccine',
    ],
    source: 'Asthma and Allergy Foundation',
  },
  {
    id: 'kidney-disease',
    name: 'Chronic Kidney Disease',
    description: 'A condition where the kidneys gradually lose function over time.',
    foodsToEat: [
      'Cauliflower',
      'Blueberries',
      'Egg whites',
      'Garlic',
      'Olive oil',
      'Red grapes',
      'Onions',
      'White rice',
    ],
    foodsToAvoid: [
      'High-sodium foods',
      'Processed meats',
      'Bananas (excess potassium)',
      'Oranges (excess potassium)',
      'Dark chocolate',
      'Nuts (excess phosphorus)',
      'Whole grains (excess phosphorus)',
      'Red meat (excess)',
    ],
    exercises: [
      'Walking',
      'Swimming',
      'Cycling',
      'Yoga',
      'Light strength training',
    ],
    lifestyle: [
      'Monitor kidney function',
      'Control blood pressure',
      'Manage diabetes if present',
      'Limit protein intake',
      'Stay hydrated',
      'Avoid NSAIDs',
    ],
    source: 'National Kidney Foundation',
  },
];

export function getHealthCondition(id: string): HealthCondition | undefined {
  return healthConditions.find(c => c.id === id);
}

export function searchHealthConditions(query: string): HealthCondition[] {
  const lower = query.toLowerCase();
  return healthConditions.filter(c =>
    c.name.toLowerCase().includes(lower) ||
    c.description.toLowerCase().includes(lower)
  );
}

export function getHealthConditionsForProfile(profile: { healthProblems: string[] }): HealthCondition[] {
  return healthConditions.filter(c =>
    profile.healthProblems.some(p =>
      c.id.includes(p.toLowerCase()) ||
      c.name.toLowerCase().includes(p.toLowerCase())
    )
  );
}
