import { FoodItem } from '../../types';

export const africanCaribbean: FoodItem[] = [
  { id: 'jollof-rice', name: 'Jollof Rice', category: 'prepared', cuisines: ['general'], nutrition: { calories: 180, protein: 4, carbohydrates: 30, fat: 5, fiber: 1.5, sugar: 2, sodium: 420 }, servingSizes: [{ label: '1 cup (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'tagine', name: 'Chicken Tagine', category: 'prepared', cuisines: ['general'], nutrition: { calories: 200, protein: 20, carbohydrates: 10, fat: 9, fiber: 2, sugar: 4, sodium: 520 }, servingSizes: [{ label: '1 serving (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: [] },
  { id: 'injera-doro-wat', name: 'Injera with Doro Wat', category: 'prepared', cuisines: ['general'], nutrition: { calories: 280, protein: 18, carbohydrates: 35, fat: 8, fiber: 3, sugar: 3, sodium: 480 }, servingSizes: [{ label: '1 serving (300g)', amount: 300, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['eggs'], tags: [] },
  { id: 'bobotie', name: 'Bobotie', category: 'prepared', cuisines: ['general'], nutrition: { calories: 220, protein: 16, carbohydrates: 14, fat: 12, fiber: 2, sugar: 4, sodium: 420 }, servingSizes: [{ label: '1 serving (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['eggs', 'dairy'], tags: [] },
  { id: 'egusi-soup', name: 'Egusi Soup', category: 'prepared', cuisines: ['general'], nutrition: { calories: 160, protein: 8, carbohydrates: 6, fat: 13, fiber: 2, sugar: 2, sodium: 380 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['gluten_free'] },
  { id: 'suya', name: 'Suya (Grilled Beef Skewers)', category: 'prepared', cuisines: ['general'], nutrition: { calories: 220, protein: 25, carbohydrates: 2, fat: 12, fiber: 0.5, sugar: 0, sodium: 420 }, servingSizes: [{ label: '1 skewer (80g)', amount: 80, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['peanuts'], tags: ['gluten_free', 'high_protein'] },
  { id: 'jerk-chicken-cb', name: 'Jerk Chicken', category: 'prepared', cuisines: ['general'], nutrition: { calories: 210, protein: 28, carbohydrates: 3, fat: 10, fiber: 1, sugar: 2, sodium: 520 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['gluten_free', 'high_protein'] },
  { id: 'rice-peas', name: 'Rice and Peas', category: 'prepared', cuisines: ['general'], nutrition: { calories: 180, protein: 5, carbohydrates: 32, fat: 3, fiber: 4, sugar: 1, sodium: 320 }, servingSizes: [{ label: '1 cup (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'fried-plantain', name: 'Fried Plantain', category: 'prepared', cuisines: ['general'], nutrition: { calories: 300, protein: 1, carbohydrates: 58, fat: 10, fiber: 2, sugar: 32, sodium: 8 }, servingSizes: [{ label: '1 cup (150g)', amount: 150, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'ackee-saltfish', name: 'Ackee and Saltfish', category: 'prepared', cuisines: ['general'], nutrition: { calories: 220, protein: 16, carbohydrates: 8, fat: 14, fiber: 3, sugar: 3, sodium: 680 }, servingSizes: [{ label: '1 serving (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['fish'], tags: [] },
  { id: 'oxtail-stew', name: 'Oxtail Stew', category: 'prepared', cuisines: ['general'], nutrition: { calories: 260, protein: 22, carbohydrates: 8, fat: 15, fiber: 2, sugar: 3, sodium: 520 }, servingSizes: [{ label: '1 serving (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: [] },
  { id: 'curry-goat', name: 'Curry Goat', category: 'prepared', cuisines: ['general'], nutrition: { calories: 240, protein: 24, carbohydrates: 6, fat: 13, fiber: 2, sugar: 2, sodium: 480 }, servingSizes: [{ label: '1 serving (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: [] },
  { id: 'pelau', name: 'Pelau', category: 'prepared', cuisines: ['general'], nutrition: { calories: 200, protein: 14, carbohydrates: 24, fat: 6, fiber: 2, sugar: 2, sodium: 420 }, servingSizes: [{ label: '1 cup (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: [] },
  { id: 'doubles', name: 'Doubles', category: 'prepared', cuisines: ['general'], nutrition: { calories: 280, protein: 8, carbohydrates: 42, fat: 9, fiber: 5, sugar: 3, sodium: 480 }, servingSizes: [{ label: '1 serving (120g)', amount: 120, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'biltong', name: 'Biltong', category: 'proteins', cuisines: ['general'], nutrition: { calories: 400, protein: 50, carbohydrates: 4, fat: 20, fiber: 0, sugar: 3, sodium: 800 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['gluten_free', 'high_protein'] },
];
