import { FoodItem } from '../../types';

export const bakingIngredients: FoodItem[] = [
  { id: 'all-purpose-flour', name: 'All-Purpose Flour', category: 'condiments', cuisines: ['general'], nutrition: { calories: 364, protein: 10, carbohydrates: 76, fat: 1, fiber: 2.7, sugar: 0.3, sodium: 2 }, servingSizes: [{ label: '1 cup (120g)', amount: 120, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'whole-wheat-flour', name: 'Whole Wheat Flour', category: 'condiments', cuisines: ['general'], nutrition: { calories: 340, protein: 13, carbohydrates: 72, fat: 2.5, fiber: 11, sugar: 0.4, sodium: 2 }, servingSizes: [{ label: '1 cup (120g)', amount: 120, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'almond-flour', name: 'Almond Flour', category: 'condiments', cuisines: ['general'], nutrition: { calories: 571, protein: 21, carbohydrates: 22, fat: 50, fiber: 11, sugar: 4.4, sodium: 0 }, servingSizes: [{ label: '1 cup (96g)', amount: 96, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['tree_nuts'], tags: ['vegan', 'gluten_free'] },
  { id: 'coconut-flour', name: 'Coconut Flour', category: 'condiments', cuisines: ['general'], nutrition: { calories: 443, protein: 19, carbohydrates: 60, fat: 12, fiber: 39, sugar: 14, sodium: 37 }, servingSizes: [{ label: '1/4 cup (28g)', amount: 28, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'cornstarch', name: 'Cornstarch', category: 'condiments', cuisines: ['general'], nutrition: { calories: 381, protein: 0.3, carbohydrates: 91, fat: 0.1, fiber: 0.9, sugar: 0, sodium: 9 }, servingSizes: [{ label: '1 tbsp (8g)', amount: 8, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'baking-powder', name: 'Baking Powder', category: 'condiments', cuisines: ['general'], nutrition: { calories: 53, protein: 0, carbohydrates: 28, fat: 0, fiber: 0, sugar: 0, sodium: 10600 }, servingSizes: [{ label: '1 tsp (4g)', amount: 4, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'baking-soda', name: 'Baking Soda', category: 'condiments', cuisines: ['general'], nutrition: { calories: 0, protein: 0, carbohydrates: 0, fat: 0, fiber: 0, sugar: 0, sodium: 27000 }, servingSizes: [{ label: '1 tsp (5g)', amount: 5, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'vanilla-extract', name: 'Vanilla Extract', category: 'condiments', cuisines: ['general'], nutrition: { calories: 288, protein: 0.1, carbohydrates: 13, fat: 0.1, fiber: 0, sugar: 13, sodium: 9 }, servingSizes: [{ label: '1 tsp (4ml)', amount: 4, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'cocoa-powder', name: 'Cocoa Powder', category: 'condiments', cuisines: ['general'], nutrition: { calories: 228, protein: 20, carbohydrates: 58, fat: 14, fiber: 33, sugar: 2, sodium: 21 }, servingSizes: [{ label: '1 tbsp (5g)', amount: 5, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'chocolate-chips', name: 'Chocolate Chips', category: 'condiments', cuisines: ['general'], nutrition: { calories: 502, protein: 5, carbohydrates: 63, fat: 30, fiber: 5, sugar: 54, sodium: 24 }, servingSizes: [{ label: '1 tbsp (15g)', amount: 15, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy', 'soy'], tags: ['vegetarian'] },
  { id: 'powdered-sugar', name: 'Powdered Sugar', category: 'condiments', cuisines: ['general'], nutrition: { calories: 389, protein: 0, carbohydrates: 100, fat: 0, fiber: 0, sugar: 100, sodium: 1 }, servingSizes: [{ label: '1 tbsp (8g)', amount: 8, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'yeast-active-dry', name: 'Yeast (Active Dry)', category: 'condiments', cuisines: ['general'], nutrition: { calories: 325, protein: 40, carbohydrates: 41, fat: 7, fiber: 27, sugar: 0, sodium: 51 }, servingSizes: [{ label: '1 packet (7g)', amount: 7, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'bread-flour', name: 'Bread Flour', category: 'condiments', cuisines: ['general'], nutrition: { calories: 361, protein: 12, carbohydrates: 72, fat: 1.7, fiber: 2.4, sugar: 0.8, sodium: 2 }, servingSizes: [{ label: '1 cup (120g)', amount: 120, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'cake-flour', name: 'Cake Flour', category: 'condiments', cuisines: ['general'], nutrition: { calories: 362, protein: 8, carbohydrates: 78, fat: 0.8, fiber: 1.7, sugar: 0.2, sodium: 2 }, servingSizes: [{ label: '1 cup (114g)', amount: 114, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'molasses', name: 'Molasses', category: 'condiments', cuisines: ['general'], nutrition: { calories: 290, protein: 0, carbohydrates: 75, fat: 0.1, fiber: 0, sugar: 55, sodium: 37 }, servingSizes: [{ label: '1 tbsp (20g)', amount: 20, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'gelatin', name: 'Gelatin', category: 'condiments', cuisines: ['general'], nutrition: { calories: 335, protein: 85, carbohydrates: 0, fat: 0.2, fiber: 0, sugar: 0, sodium: 196 }, servingSizes: [{ label: '1 packet (7g)', amount: 7, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['gluten_free'] },
  { id: 'agar-agar', name: 'Agar Agar', category: 'condiments', cuisines: ['general'], nutrition: { calories: 306, protein: 1, carbohydrates: 96, fat: 0.3, fiber: 0, sugar: 0, sodium: 40 }, servingSizes: [{ label: '1 tsp (2g)', amount: 2, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
];
