import { FoodItem } from '../../types';

export const beverages: FoodItem[] = [
  { id: 'water', name: 'Water', category: 'beverages', cuisines: ['general'], nutrition: { calories: 0, protein: 0, carbohydrates: 0, fat: 0, fiber: 0, sugar: 0, sodium: 0 }, servingSizes: [{ label: '1 glass (250ml)', amount: 250, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'black-coffee', name: 'Black Coffee', category: 'beverages', cuisines: ['general'], nutrition: { calories: 2, protein: 0.3, carbohydrates: 0, fat: 0, fiber: 0, sugar: 0, sodium: 5 }, servingSizes: [{ label: '1 cup (240ml)', amount: 240, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'green-tea', name: 'Green Tea', category: 'beverages', cuisines: ['general'], nutrition: { calories: 1, protein: 0, carbohydrates: 0, fat: 0, fiber: 0, sugar: 0, sodium: 1 }, servingSizes: [{ label: '1 cup (240ml)', amount: 240, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'chai-tea', name: 'Chai Tea (Indian)', category: 'beverages', cuisines: ['indian'], nutrition: { calories: 45, protein: 0.5, carbohydrates: 8, fat: 1.5, fiber: 0, sugar: 6, sodium: 10 }, servingSizes: [{ label: '1 cup (200ml)', amount: 200, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'masala-chai', name: 'Masala Chai', category: 'beverages', cuisines: ['indian'], nutrition: { calories: 55, protein: 0.8, carbohydrates: 10, fat: 1.8, fiber: 0, sugar: 7, sodium: 12 }, servingSizes: [{ label: '1 cup (200ml)', amount: 200, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'orange-juice', name: 'Orange Juice', category: 'beverages', cuisines: ['general'], nutrition: { calories: 45, protein: 0.7, carbohydrates: 10, fat: 0.2, fiber: 0.2, sugar: 8, sodium: 1 }, servingSizes: [{ label: '1 cup (240ml)', amount: 240, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'apple-juice', name: 'Apple Juice', category: 'beverages', cuisines: ['general'], nutrition: { calories: 46, protein: 0.1, carbohydrates: 11, fat: 0.1, fiber: 0, sugar: 10, sodium: 4 }, servingSizes: [{ label: '1 cup (248ml)', amount: 248, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'coconut-water', name: 'Coconut Water', category: 'beverages', cuisines: ['general'], nutrition: { calories: 19, protein: 0.7, carbohydrates: 4, fat: 0.2, fiber: 1.1, sugar: 2.6, sodium: 105 }, servingSizes: [{ label: '1 cup (240ml)', amount: 240, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'mango-lassi', name: 'Mango Lassi', category: 'beverages', cuisines: ['indian'], nutrition: { calories: 148, protein: 4.5, carbohydrates: 26, fat: 2.5, fiber: 0.5, sugar: 22, sodium: 55 }, servingSizes: [{ label: '1 glass (250ml)', amount: 250, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'buttermilk-drink', name: 'Chaas (Buttermilk Drink)', category: 'beverages', cuisines: ['indian'], nutrition: { calories: 27, protein: 3.3, carbohydrates: 4.8, fat: 0.4, fiber: 0, sugar: 4.8, sodium: 105 }, servingSizes: [{ label: '1 glass (250ml)', amount: 250, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'soda', name: 'Soda (Cola)', category: 'beverages', cuisines: ['general'], nutrition: { calories: 42, protein: 0, carbohydrates: 11, fat: 0, fiber: 0, sugar: 11, sodium: 4 }, servingSizes: [{ label: '1 can (330ml)', amount: 330, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'beer', name: 'Beer', category: 'beverages', cuisines: ['general'], nutrition: { calories: 43, protein: 0.5, carbohydrates: 3.6, fat: 0, fiber: 0, sugar: 0.3, sodium: 4 }, servingSizes: [{ label: '1 bottle (355ml)', amount: 355, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'wine', name: 'Red Wine', category: 'beverages', cuisines: ['general'], nutrition: { calories: 83, protein: 0.1, carbohydrates: 2.6, fat: 0, fiber: 0, sugar: 0.6, sodium: 4 }, servingSizes: [{ label: '1 glass (150ml)', amount: 150, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'protein-shake', name: 'Protein Shake', category: 'beverages', cuisines: ['general'], nutrition: { calories: 120, protein: 24, carbohydrates: 3, fat: 1.5, fiber: 0, sugar: 1, sodium: 150 }, servingSizes: [{ label: '1 scoop (31g) + 250ml water', amount: 281, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy', 'soy'], tags: ['gluten_free', 'high_protein'] },
  { id: 'banana-shake', name: 'Banana Shake', category: 'beverages', cuisines: ['general'], nutrition: { calories: 130, protein: 3.5, carbohydrates: 24, fat: 3, fiber: 1.2, sugar: 20, sodium: 40 }, servingSizes: [{ label: '1 glass (300ml)', amount: 300, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['dairy'], tags: ['vegetarian'] },
];
