import { FoodItem } from '../../types';

export const chineseDishes: FoodItem[] = [
  { id: 'fried-rice-chinese', name: 'Egg Fried Rice', category: 'prepared', cuisines: ['chinese'], nutrition: { calories: 180, protein: 5, carbohydrates: 26, fat: 6.5, fiber: 0.8, sugar: 0.4, sodium: 425 }, servingSizes: [{ label: '1 cup (190g)', amount: 190, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['eggs', 'soy'], tags: [] },
  { id: 'kung-pao-chicken', name: 'Kung Pao Chicken', category: 'prepared', cuisines: ['chinese'], nutrition: { calories: 230, protein: 20, carbohydrates: 10, fat: 13, fiber: 2, sugar: 4, sodium: 680 }, servingSizes: [{ label: '1 cup (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['peanuts', 'soy'], tags: ['gluten_free'] },
  { id: 'sweet-sour-pork', name: 'Sweet and Sour Pork', category: 'prepared', cuisines: ['chinese'], nutrition: { calories: 280, protein: 15, carbohydrates: 25, fat: 14, fiber: 1, sugar: 12, sodium: 520 }, servingSizes: [{ label: '1 cup (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['soy', 'gluten'], tags: [] },
  { id: 'mapo-tofu', name: 'Mapo Tofu', category: 'prepared', cuisines: ['chinese'], nutrition: { calories: 180, protein: 12, carbohydrates: 6, fat: 13, fiber: 1.5, sugar: 2, sodium: 650 }, servingSizes: [{ label: '1 cup (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['soy'], tags: ['spicy'] },
  { id: 'spring-roll', name: 'Spring Roll (Vegetable)', category: 'prepared', cuisines: ['chinese'], nutrition: { calories: 210, protein: 3, carbohydrates: 22, fat: 12, fiber: 1.5, sugar: 2, sodium: 420 }, servingSizes: [{ label: '2 rolls (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'dim-sum', name: 'Dim Sum (Prawn)', category: 'prepared', cuisines: ['chinese'], nutrition: { calories: 150, protein: 10, carbohydrates: 18, fat: 4, fiber: 1, sugar: 1, sodium: 480 }, servingSizes: [{ label: '3 pieces (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['shellfish', 'gluten'], tags: [] },
  { id: 'wonton-soup', name: 'Wonton Soup', category: 'prepared', cuisines: ['chinese'], nutrition: { calories: 110, protein: 8, carbohydrates: 12, fat: 3, fiber: 1, sugar: 1, sodium: 680 }, servingSizes: [{ label: '1 bowl (300g)', amount: 300, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'shellfish'], tags: [] },
  { id: 'chow-mein', name: 'Vegetable Chow Mein', category: 'prepared', cuisines: ['chinese'], nutrition: { calories: 170, protein: 5, carbohydrates: 25, fat: 6, fiber: 2, sugar: 3, sodium: 520 }, servingSizes: [{ label: '1 cup (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'soy'], tags: ['vegan'] },
  { id: 'peking-duck', name: 'Peking Duck', category: 'prepared', cuisines: ['chinese'], nutrition: { calories: 340, protein: 25, carbohydrates: 12, fat: 22, fiber: 0.5, sugar: 5, sodium: 580 }, servingSizes: [{ label: '1 serving (150g)', amount: 150, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['gluten_free'] },
  { id: 'hot-sour-soup', name: 'Hot and Sour Soup', category: 'prepared', cuisines: ['chinese'], nutrition: { calories: 80, protein: 5, carbohydrates: 8, fat: 3, fiber: 1, sugar: 2, sodium: 850 }, servingSizes: [{ label: '1 bowl (300g)', amount: 300, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['soy', 'eggs'], tags: ['spicy'] },
  { id: 'szechuan-noodles', name: 'Szechuan Noodles', category: 'prepared', cuisines: ['chinese'], nutrition: { calories: 220, protein: 8, carbohydrates: 32, fat: 7, fiber: 2, sugar: 3, sodium: 650 }, servingSizes: [{ label: '1 bowl (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'soy'], tags: ['spicy'] },
  { id: 'fried-momos', name: 'Fried Momos (Dumplings)', category: 'prepared', cuisines: ['chinese'], nutrition: { calories: 250, protein: 8, carbohydrates: 28, fat: 12, fiber: 2, sugar: 1, sodium: 480 }, servingSizes: [{ label: '4 pieces (120g)', amount: 120, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: [] },
  { id: 'steamed-momos', name: 'Steamed Momos (Vegetable)', category: 'prepared', cuisines: ['chinese'], nutrition: { calories: 140, protein: 4, carbohydrates: 22, fat: 4, fiber: 2, sugar: 1, sodium: 380 }, servingSizes: [{ label: '4 pieces (120g)', amount: 120, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'tofu-stirfry', name: 'Tofu Stir-Fry', category: 'prepared', cuisines: ['chinese'], nutrition: { calories: 160, protein: 10, carbohydrates: 10, fat: 9, fiber: 2, sugar: 3, sodium: 520 }, servingSizes: [{ label: '1 cup (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['soy'], tags: ['vegan'] },
];
