import { FoodItem } from '../../types';

export const dairy: FoodItem[] = [
  { id: 'whole-milk', name: 'Whole Milk', category: 'dairy', cuisines: ['general'], nutrition: { calories: 61, protein: 3.2, carbohydrates: 4.8, fat: 3.3, fiber: 0, sugar: 5.1, sodium: 43 }, servingSizes: [{ label: '1 cup (244ml)', amount: 244, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'skim-milk', name: 'Skim Milk', category: 'dairy', cuisines: ['general'], nutrition: { calories: 34, protein: 3.4, carbohydrates: 5, fat: 0.1, fiber: 0, sugar: 5.1, sodium: 42 }, servingSizes: [{ label: '1 cup (245ml)', amount: 245, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'yogurt', name: 'Plain Yogurt', category: 'dairy', cuisines: ['indian', 'general'], nutrition: { calories: 63, protein: 5.3, carbohydrates: 7, fat: 1.6, fiber: 0, sugar: 7, sodium: 70 }, servingSizes: [{ label: '1 cup (245g)', amount: 245, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'greek-yogurt', name: 'Greek Yogurt', category: 'dairy', cuisines: ['general'], nutrition: { calories: 59, protein: 10, carbohydrates: 3.6, fat: 0.7, fiber: 0, sugar: 3.2, sodium: 36 }, servingSizes: [{ label: '1 cup (245g)', amount: 245, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'cheese-cheddar', name: 'Cheddar Cheese', category: 'dairy', cuisines: ['general'], nutrition: { calories: 403, protein: 25, carbohydrates: 1.3, fat: 33, fiber: 0, sugar: 0.5, sodium: 621 }, servingSizes: [{ label: '1 slice (28g)', amount: 28, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'cheese-mozzarella', name: 'Mozzarella Cheese', category: 'dairy', cuisines: ['italian', 'general'], nutrition: { calories: 280, protein: 28, carbohydrates: 3.1, fat: 17, fiber: 0, sugar: 1, sodium: 627 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'cheese-paneer', name: 'Paneer (Indian Cottage Cheese)', category: 'dairy', cuisines: ['indian'], nutrition: { calories: 265, protein: 20, carbohydrates: 4, fat: 20, fiber: 0, sugar: 3.5, sodium: 49 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'cottage-cheese', name: 'Cottage Cheese', category: 'dairy', cuisines: ['general'], nutrition: { calories: 98, protein: 11, carbohydrates: 3.4, fat: 4.3, fiber: 0, sugar: 3.7, sodium: 364 }, servingSizes: [{ label: '1/2 cup (113g)', amount: 113, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'butter', name: 'Butter', category: 'dairy', cuisines: ['general'], nutrition: { calories: 717, protein: 0.9, carbohydrates: 0.1, fat: 81, fiber: 0, sugar: 0.1, sodium: 11 }, servingSizes: [{ label: '1 tbsp (14g)', amount: 14, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian', 'gluten_free'] },
  { id: 'ghee', name: 'Ghee (Clarified Butter)', category: 'dairy', cuisines: ['indian'], nutrition: { calories: 900, protein: 0, carbohydrates: 0, fat: 100, fiber: 0, sugar: 0, sodium: 0 }, servingSizes: [{ label: '1 tbsp (15ml)', amount: 15, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['dairy'], tags: ['gluten_free'] },
  { id: 'cream', name: 'Heavy Cream', category: 'dairy', cuisines: ['general'], nutrition: { calories: 340, protein: 2.1, carbohydrates: 2.8, fat: 36, fiber: 0, sugar: 2.9, sodium: 34 }, servingSizes: [{ label: '1 tbsp (15ml)', amount: 15, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['dairy'], tags: ['vegetarian', 'gluten_free'] },
  { id: 'buttermilk', name: 'Buttermilk (Chaas)', category: 'dairy', cuisines: ['indian'], nutrition: { calories: 27, protein: 3.3, carbohydrates: 4.8, fat: 0.4, fiber: 0, sugar: 4.8, sodium: 105 }, servingSizes: [{ label: '1 cup (242ml)', amount: 242, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'lassi', name: 'Sweet Lassi', category: 'dairy', cuisines: ['indian'], nutrition: { calories: 120, protein: 4, carbohydrates: 18, fat: 3, fiber: 0, sugar: 16, sodium: 50 }, servingSizes: [{ label: '1 glass (250ml)', amount: 250, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'ice-cream', name: 'Ice Cream (Vanilla)', category: 'dairy', cuisines: ['general'], nutrition: { calories: 207, protein: 3.5, carbohydrates: 24, fat: 11, fiber: 0, sugar: 21, sodium: 80 }, servingSizes: [{ label: '1 scoop (66g)', amount: 66, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'milk-powder', name: 'Milk Powder', category: 'dairy', cuisines: ['general'], nutrition: { calories: 496, protein: 26, carbohydrates: 38, fat: 27, fiber: 0, sugar: 38, sodium: 371 }, servingSizes: [{ label: '1 cup (128g)', amount: 128, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'custard', name: 'Custard Powder', category: 'dairy', cuisines: ['general'], nutrition: { calories: 356, protein: 2, carbohydrates: 83, fat: 0.8, fiber: 0, sugar: 45, sodium: 10 }, servingSizes: [{ label: '100g dry', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: ['vegetarian'] },
];
