import { FoodItem } from '../../types';

export const japaneseExtra: FoodItem[] = [
  { id: 'teriyaki-chicken-jp', name: 'Teriyaki Chicken', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 220, protein: 24, carbohydrates: 10, fat: 10, fiber: 0, sugar: 8, sodium: 520 }, servingSizes: [{ label: '1 serving (150g)', amount: 150, unit: 'g' }], allergens: ['soy', 'gluten'], tags: ['high_protein'] },
  { id: 'tonkatsu', name: 'Tonkatsu', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 350, protein: 25, carbohydrates: 18, fat: 22, fiber: 1, sugar: 3, sodium: 440 }, servingSizes: [{ label: '1 cutlet (150g)', amount: 150, unit: 'g' }], allergens: ['gluten', 'eggs'], tags: [] },
  { id: 'chicken-katsu', name: 'Chicken Katsu', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 280, protein: 24, carbohydrates: 16, fat: 14, fiber: 1, sugar: 2, sodium: 420 }, servingSizes: [{ label: '1 cutlet (150g)', amount: 150, unit: 'g' }], allergens: ['gluten', 'eggs'], tags: [] },
  { id: 'gyoza', name: 'Gyoza (Dumplings)', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 200, protein: 10, carbohydrates: 18, fat: 10, fiber: 1, sugar: 1, sodium: 400 }, servingSizes: [{ label: '6 pieces (120g)', amount: 120, unit: 'g' }], allergens: ['gluten', 'soy'], tags: [] },
  { id: 'okonomiyaki', name: 'Okonomiyaki', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 250, protein: 12, carbohydrates: 25, fat: 12, fiber: 2, sugar: 5, sodium: 520 }, servingSizes: [{ label: '1 serving (200g)', amount: 200, unit: 'g' }], allergens: ['gluten', 'eggs', 'shellfish'], tags: [] },
  { id: 'takoyaki', name: 'Takoyaki', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 200, protein: 8, carbohydrates: 22, fat: 10, fiber: 1, sugar: 3, sodium: 460 }, servingSizes: [{ label: '6 pieces (120g)', amount: 120, unit: 'g' }], allergens: ['gluten', 'eggs', 'shellfish'], tags: [] },
  { id: 'yakisoba', name: 'Yakisoba', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 240, protein: 8, carbohydrates: 35, fat: 8, fiber: 2, sugar: 6, sodium: 540 }, servingSizes: [{ label: '1 serving (200g)', amount: 200, unit: 'g' }], allergens: ['gluten', 'soy'], tags: ['vegan'] },
  { id: 'omurice', name: 'Omurice', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 280, protein: 12, carbohydrates: 32, fat: 12, fiber: 1, sugar: 4, sodium: 420 }, servingSizes: [{ label: '1 serving (250g)', amount: 250, unit: 'g' }], allergens: ['eggs', 'soy'], tags: [] },
  { id: 'karaage', name: 'Karaage (Japanese Fried Chicken)', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 280, protein: 22, carbohydrates: 12, fat: 18, fiber: 0, sugar: 1, sodium: 400 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'soy', 'eggs'], tags: [] },
  { id: 'nikujaga', name: 'Nikujaga', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 150, protein: 10, carbohydrates: 16, fat: 6, fiber: 2, sugar: 4, sodium: 380 }, servingSizes: [{ label: '1 serving (200g)', amount: 200, unit: 'g' }], allergens: ['soy'], tags: [] },
  { id: 'chawanmushi', name: 'Chawanmushi', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 80, protein: 6, carbohydrates: 2, fat: 5, fiber: 0, sugar: 1, sodium: 320 }, servingSizes: [{ label: '1 cup (100g)', amount: 100, unit: 'g' }], allergens: ['eggs', 'soy'], tags: ['gluten_free'] },
  { id: 'miso-soup-extra', name: 'Miso Soup (Extra)', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 40, protein: 3, carbohydrates: 5, fat: 1, fiber: 1, sugar: 1, sodium: 480 }, servingSizes: [{ label: '1 bowl (250ml)', amount: 250, unit: 'ml' }], allergens: ['soy'], tags: ['vegan', 'gluten_free'] },
  { id: 'udon-soup', name: 'Udon Noodle Soup', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 200, protein: 8, carbohydrates: 38, fat: 2, fiber: 2, sugar: 4, sodium: 560 }, servingSizes: [{ label: '1 bowl (350g)', amount: 350, unit: 'g' }], allergens: ['gluten', 'soy'], tags: [] },
  { id: 'soba-noodles', name: 'Soba Noodles', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 180, protein: 8, carbohydrates: 36, fat: 1, fiber: 3, sugar: 2, sodium: 0 }, servingSizes: [{ label: '1 serving (150g)', amount: 150, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'chashu-pork', name: 'Chashu Pork', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 300, protein: 18, carbohydrates: 4, fat: 24, fiber: 0, sugar: 2, sodium: 420 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }], allergens: ['soy'], tags: ['high_protein'] },
];

export const koreanExtra: FoodItem[] = [
  { id: 'bibimbap-extra', name: 'Bibimbap (Extra)', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 250, protein: 12, carbohydrates: 38, fat: 6, fiber: 4, sugar: 4, sodium: 480 }, servingSizes: [{ label: '1 bowl (300g)', amount: 300, unit: 'g' }], allergens: ['soy', 'eggs'], tags: [] },
  { id: 'tteokbokki-extra', name: 'Tteokbokki (Extra)', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 280, protein: 6, carbohydrates: 52, fat: 5, fiber: 2, sugar: 12, sodium: 600 }, servingSizes: [{ label: '1 serving (200g)', amount: 200, unit: 'g' }], allergens: ['gluten', 'soy', 'fish'], tags: ['spicy'] },
  { id: 'jjajangmyeon', name: 'Jjajangmyeon', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 400, protein: 14, carbohydrates: 65, fat: 10, fiber: 4, sugar: 8, sodium: 580 }, servingSizes: [{ label: '1 bowl (350g)', amount: 350, unit: 'g' }], allergens: ['gluten', 'soy'], tags: [] },
  { id: 'japchae', name: 'Japchae', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 180, protein: 5, carbohydrates: 28, fat: 6, fiber: 2, sugar: 5, sodium: 420 }, servingSizes: [{ label: '1 serving (150g)', amount: 150, unit: 'g' }], allergens: ['soy', 'gluten'], tags: [] },
  { id: 'samgyeopsal', name: 'Samgyeopsal (Grilled Pork Belly)', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 350, protein: 14, carbohydrates: 0, fat: 34, fiber: 0, sugar: 0, sodium: 80 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['gluten_free', 'high_protein'] },
  { id: 'galbi', name: 'Galbi (Grilled Ribs)', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 300, protein: 22, carbohydrates: 10, fat: 20, fiber: 0, sugar: 8, sodium: 480 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }], allergens: ['soy', 'gluten'], tags: ['high_protein'] },
  { id: 'sundubu-jjigae', name: 'Sundubu Jjigae', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 120, protein: 8, carbohydrates: 10, fat: 6, fiber: 2, sugar: 3, sodium: 500 }, servingSizes: [{ label: '1 bowl (250g)', amount: 250, unit: 'g' }], allergens: ['soy', 'shellfish'], tags: ['spicy'] },
  { id: 'bulgogi-2', name: 'Bulgogi (Extra)', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 240, protein: 22, carbohydrates: 12, fat: 12, fiber: 1, sugar: 8, sodium: 460 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }], allergens: ['soy', 'peanuts'], tags: ['high_protein'] },
  { id: 'kimchi-jjigae', name: 'Kimchi Jjigae', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 130, protein: 10, carbohydrates: 8, fat: 7, fiber: 2, sugar: 3, sodium: 560 }, servingSizes: [{ label: '1 bowl (250g)', amount: 250, unit: 'g' }], allergens: ['soy'], tags: ['spicy'] },
  { id: 'kimbap', name: 'Kimbap', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 220, protein: 8, carbohydrates: 35, fat: 5, fiber: 2, sugar: 3, sodium: 420 }, servingSizes: [{ label: '1 roll (120g)', amount: 120, unit: 'g' }], allergens: ['soy', 'gluten', 'eggs'], tags: [] },
  { id: 'hotteok', name: 'Hotteok', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 250, protein: 4, carbohydrates: 42, fat: 8, fiber: 1, sugar: 15, sodium: 200 }, servingSizes: [{ label: '1 piece (80g)', amount: 80, unit: 'g' }], allergens: ['gluten'], tags: [] },
  { id: 'haemul-pajeon', name: 'Haemul Pajeon', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 220, protein: 12, carbohydrates: 22, fat: 10, fiber: 2, sugar: 2, sodium: 480 }, servingSizes: [{ label: '1 serving (120g)', amount: 120, unit: 'g' }], allergens: ['gluten', 'shellfish', 'eggs'], tags: [] },
  { id: 'seolleongtang', name: 'Seolleongtang', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 120, protein: 10, carbohydrates: 6, fat: 6, fiber: 1, sugar: 1, sodium: 440 }, servingSizes: [{ label: '1 bowl (350ml)', amount: 350, unit: 'ml' }], allergens: ['gluten'], tags: ['gluten_free'] },
  { id: 'naengmyeon', name: 'Naengmyeon', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 280, protein: 8, carbohydrates: 52, fat: 4, fiber: 2, sugar: 6, sodium: 520 }, servingSizes: [{ label: '1 bowl (300g)', amount: 300, unit: 'g' }], allergens: ['gluten', 'eggs'], tags: [] },
  { id: 'chimchae', name: 'Chimchae (Cold Noodles)', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 240, protein: 6, carbohydrates: 45, fat: 4, fiber: 2, sugar: 8, sodium: 480 }, servingSizes: [{ label: '1 bowl (300g)', amount: 300, unit: 'g' }], allergens: ['gluten'], tags: [] },
];
