import { FoodItem } from '../../types';

export const fatsSpreads: FoodItem[] = [
  { id: 'margarine', name: 'Margarine', category: 'oils', cuisines: ['general'], nutrition: { calories: 717, protein: 0, carbohydrates: 0, fat: 81, fiber: 0, sugar: 0, sodium: 640 }, servingSizes: [{ label: '1 tbsp (14g)', amount: 14, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'coconut-butter', name: 'Coconut Butter', category: 'oils', cuisines: ['general'], nutrition: { calories: 623, protein: 3.3, carbohydrates: 14, fat: 66, fiber: 12, sugar: 6, sodium: 20 }, servingSizes: [{ label: '1 tbsp (16g)', amount: 16, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'pesto-basil', name: 'Pesto (Basil)', category: 'condiments', cuisines: ['italian'], nutrition: { calories: 400, protein: 5, carbohydrates: 4, fat: 42, fiber: 2, sugar: 1, sodium: 800 }, servingSizes: [{ label: '2 tbsp (30g)', amount: 30, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy', 'nuts', 'tree_nuts'], tags: ['vegetarian'] },
  { id: 'sunflower-seed-butter', name: 'Sunflower Seed Butter', category: 'condiments', cuisines: ['general'], nutrition: { calories: 614, protein: 16, carbohydrates: 22, fat: 52, fiber: 9, sugar: 10, sodium: 4 }, servingSizes: [{ label: '2 tbsp (32g)', amount: 32, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'hazelnut-spread', name: 'Hazelnut Spread', category: 'condiments', cuisines: ['general'], nutrition: { calories: 540, protein: 6, carbohydrates: 57, fat: 32, fiber: 3, sugar: 54, sodium: 42 }, servingSizes: [{ label: '2 tbsp (37g)', amount: 37, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['tree_nuts', 'dairy'], tags: ['vegetarian'] },
  { id: 'jam-strawberry', name: 'Jam (Strawberry)', category: 'condiments', cuisines: ['general'], nutrition: { calories: 260, protein: 0.4, carbohydrates: 68, fat: 0, fiber: 0.6, sugar: 60, sodium: 13 }, servingSizes: [{ label: '1 tbsp (20g)', amount: 20, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'cream-cheese', name: 'Cream Cheese', category: 'dairy', cuisines: ['general'], nutrition: { calories: 342, protein: 6, carbohydrates: 4, fat: 34, fiber: 0, sugar: 3.8, sodium: 321 }, servingSizes: [{ label: '2 tbsp (30g)', amount: 30, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian', 'gluten_free'] },
  { id: 'apple-butter', name: 'Apple Butter', category: 'condiments', cuisines: ['general'], nutrition: { calories: 160, protein: 0.2, carbohydrates: 42, fat: 0, fiber: 0.5, sugar: 40, sodium: 12 }, servingSizes: [{ label: '1 tbsp (20g)', amount: 20, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
];
