import { FoodItem } from '../../types';

export const fruitsTropical: FoodItem[] = [
  { id: 'cherimoya', name: 'Cherimoya', category: 'fruits', cuisines: ['general'], nutrition: { calories: 75, protein: 2, carbohydrates: 18, fat: 0.7, fiber: 3, sugar: 12, sodium: 7 }, servingSizes: [{ label: '1 medium (160g)', amount: 160, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'feijoa', name: 'Feijoa', category: 'fruits', cuisines: ['general'], nutrition: { calories: 55, protein: 0.6, carbohydrates: 13, fat: 0.6, fiber: 6.4, sugar: 8, sodium: 2 }, servingSizes: [{ label: '1 fruit (50g)', amount: 50, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'finger-lime', name: 'Finger Lime', category: 'fruits', cuisines: ['general'], nutrition: { calories: 44, protein: 1, carbohydrates: 11, fat: 0.5, fiber: 3, sugar: 2, sodium: 5 }, servingSizes: [{ label: '1 fruit (15g)', amount: 15, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'black-sapote', name: 'Black Sapote', category: 'fruits', cuisines: ['general'], nutrition: { calories: 101, protein: 1.1, carbohydrates: 25, fat: 0.5, fiber: 3, sugar: 15, sodium: 4 }, servingSizes: [{ label: '1 fruit (150g)', amount: 150, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'canistel', name: 'Canistel (Egg Fruit)', category: 'fruits', cuisines: ['general'], nutrition: { calories: 107, protein: 1.8, carbohydrates: 27, fat: 0.2, fiber: 2.5, sugar: 15, sodium: 2 }, servingSizes: [{ label: '1 fruit (120g)', amount: 120, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'salak', name: 'Salak (Snake Fruit)', category: 'fruits', cuisines: ['general'], nutrition: { calories: 82, protein: 1, carbohydrates: 20, fat: 0.4, fiber: 2.7, sugar: 12, sodium: 2 }, servingSizes: [{ label: '1 fruit (60g)', amount: 60, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'rose-apple', name: 'Rose Apple', category: 'fruits', cuisines: ['general'], nutrition: { calories: 25, protein: 0.6, carbohydrates: 6, fat: 0.3, fiber: 0.9, sugar: 6, sodium: 0 }, servingSizes: [{ label: '1 fruit (60g)', amount: 60, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'langsat', name: 'Langsat', category: 'fruits', cuisines: ['general'], nutrition: { calories: 57, protein: 1, carbohydrates: 14, fat: 0.1, fiber: 1.3, sugar: 12, sodium: 2 }, servingSizes: [{ label: '1 fruit (15g)', amount: 15, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'santol', name: 'Santol', category: 'fruits', cuisines: ['general'], nutrition: { calories: 76, protein: 1, carbohydrates: 19, fat: 0.1, fiber: 1.8, sugar: 12, sodium: 1 }, servingSizes: [{ label: '1 fruit (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'pulasan', name: 'Pulasan', category: 'fruits', cuisines: ['general'], nutrition: { calories: 78, protein: 1, carbohydrates: 20, fat: 0.2, fiber: 1, sugar: 16, sodium: 1 }, servingSizes: [{ label: '1 fruit (50g)', amount: 50, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'cupuacu', name: 'Cupuaçu', category: 'fruits', cuisines: ['general'], nutrition: { calories: 69, protein: 1.2, carbohydrates: 16, fat: 1.1, fiber: 3.3, sugar: 9, sodium: 2 }, servingSizes: [{ label: '1 fruit (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'abiu', name: 'Abiu', category: 'fruits', cuisines: ['general'], nutrition: { calories: 79, protein: 1, carbohydrates: 19, fat: 0.4, fiber: 2.5, sugar: 8, sodium: 3 }, servingSizes: [{ label: '1 fruit (60g)', amount: 60, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'bacuri', name: 'Bacuri', category: 'fruits', cuisines: ['general'], nutrition: { calories: 103, protein: 1.5, carbohydrates: 20, fat: 3.5, fiber: 2, sugar: 12, sodium: 5 }, servingSizes: [{ label: '1 fruit (80g)', amount: 80, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'camu-camu', name: 'Camu Camu', category: 'fruits', cuisines: ['general'], nutrition: { calories: 25, protein: 0.4, carbohydrates: 6, fat: 0.2, fiber: 1, sugar: 3, sodium: 3 }, servingSizes: [{ label: '1 fruit (10g)', amount: 10, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
];
