import { FoodItem } from '../../types';

export const indianDishesExtra2: FoodItem[] = [
  // Rice Dishes
  { id: 'jeera-rice', name: 'Jeera Rice', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 180, protein: 3.5, carbohydrates: 32, fat: 4, fiber: 1, sugar: 0.5, sodium: 320 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'peas-pulao', name: 'Peas Pulao', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 175, protein: 4, carbohydrates: 30, fat: 4, fiber: 2, sugar: 1, sodium: 340 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'lemon-rice', name: 'Lemon Rice', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 170, protein: 3, carbohydrates: 28, fat: 5, fiber: 1, sugar: 1, sodium: 350 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'tamarind-rice', name: 'Tamarind Rice', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 185, protein: 3.5, carbohydrates: 30, fat: 6, fiber: 1.5, sugar: 3, sodium: 380 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'coconut-rice', name: 'Coconut Rice', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 195, protein: 3.5, carbohydrates: 28, fat: 8, fiber: 1.5, sugar: 1, sodium: 320 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'tomato-rice', name: 'Tomato Rice', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 175, protein: 3.5, carbohydrates: 29, fat: 5, fiber: 1.5, sugar: 2, sodium: 360 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'mutton-biryani', name: 'Mutton Biryani', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 240, protein: 18, carbohydrates: 28, fat: 8, fiber: 1, sugar: 1, sodium: 600 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }], allergens: [], tags: [] },
  { id: 'egg-biryani', name: 'Egg Biryani', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 200, protein: 10, carbohydrates: 28, fat: 6, fiber: 1, sugar: 1, sodium: 550 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }], allergens: ['eggs'], tags: [] },

  // Breads
  { id: 'roti', name: 'Roti (Chapati)', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 120, protein: 3.5, carbohydrates: 22, fat: 2, fiber: 3, sugar: 0.5, sodium: 280 }, servingSizes: [{ label: '1 piece (40g)', amount: 40, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'naan', name: 'Naan', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 210, protein: 6, carbohydrates: 35, fat: 5, fiber: 2, sugar: 2, sodium: 420 }, servingSizes: [{ label: '1 piece (80g)', amount: 80, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: ['vegetarian'] },
  { id: 'butter-naan', name: 'Butter Naan', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 250, protein: 6, carbohydrates: 35, fat: 10, fiber: 1.5, sugar: 2, sodium: 450 }, servingSizes: [{ label: '1 piece (80g)', amount: 80, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: ['vegetarian'] },
  { id: 'garlic-naan', name: 'Garlic Naan', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 240, protein: 6, carbohydrates: 34, fat: 9, fiber: 1.5, sugar: 2, sodium: 480 }, servingSizes: [{ label: '1 piece (80g)', amount: 80, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: ['vegetarian'] },
  { id: 'paratha', name: 'Plain Paratha', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 250, protein: 5, carbohydrates: 35, fat: 10, fiber: 2, sugar: 1, sodium: 380 }, servingSizes: [{ label: '1 piece (70g)', amount: 70, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'aloo-paratha', name: 'Aloo Paratha', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 300, protein: 6, carbohydrates: 42, fat: 12, fiber: 3, sugar: 2, sodium: 420 }, servingSizes: [{ label: '1 piece (100g)', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegetarian'] },
  { id: 'paneer-paratha', name: 'Paneer Paratha', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 320, protein: 10, carbohydrates: 38, fat: 14, fiber: 2, sugar: 2, sodium: 440 }, servingSizes: [{ label: '1 piece (100g)', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: ['vegetarian'] },
  { id: 'puri', name: 'Puri', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 150, protein: 3, carbohydrates: 20, fat: 7, fiber: 1.5, sugar: 0.5, sodium: 280 }, servingSizes: [{ label: '1 piece (40g)', amount: 40, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'bhatura', name: 'Bhatura', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 220, protein: 5, carbohydrates: 30, fat: 10, fiber: 1.5, sugar: 2, sodium: 350 }, servingSizes: [{ label: '1 piece (70g)', amount: 70, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },

  // South Indian
  { id: 'idli', name: 'Idli', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 75, protein: 2.5, carbohydrates: 15, fat: 0.5, fiber: 0.5, sugar: 0.5, sodium: 280 }, servingSizes: [{ label: '2 pieces (100g)', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'vada', name: 'Medu Vada', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 150, protein: 6, carbohydrates: 18, fat: 6, fiber: 2, sugar: 1, sodium: 320 }, servingSizes: [{ label: '2 pieces (80g)', amount: 80, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'rava-dosa', name: 'Rava Dosa', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 130, protein: 3, carbohydrates: 20, fat: 4, fiber: 1, sugar: 1, sodium: 350 }, servingSizes: [{ label: '1 dosa (100g)', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'paper-dosa', name: 'Paper Dosa', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 110, protein: 2.5, carbohydrates: 18, fat: 3, fiber: 1, sugar: 0.5, sodium: 320 }, servingSizes: [{ label: '1 dosa (80g)', amount: 80, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'uttapam-veg', name: 'Vegetable Uttapam', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 160, protein: 5, carbohydrates: 24, fat: 5, fiber: 2.5, sugar: 2, sodium: 380 }, servingSizes: [{ label: '1 piece (120g)', amount: 120, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'appam', name: 'Appam', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 120, protein: 2, carbohydrates: 22, fat: 2.5, fiber: 1, sugar: 1, sodium: 280 }, servingSizes: [{ label: '1 piece (80g)', amount: 80, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'puttu', name: 'Puttu', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 150, protein: 3, carbohydrates: 28, fat: 2.5, fiber: 1, sugar: 3, sodium: 300 }, servingSizes: [{ label: '1 piece (100g)', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan'] },

  // Curries & Gravies
  { id: 'chicken-curry', name: 'Chicken Curry', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 200, protein: 20, carbohydrates: 6, fat: 11, fiber: 1, sugar: 2, sodium: 520 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['gluten_free'] },
  { id: 'mutton-curry', name: 'Mutton Curry', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 250, protein: 22, carbohydrates: 5, fat: 16, fiber: 1, sugar: 2, sodium: 540 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['gluten_free'] },
  { id: 'fish-moilee', name: 'Fish Moilee', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 180, protein: 18, carbohydrates: 5, fat: 10, fiber: 1, sugar: 2, sodium: 480 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: ['fish'], tags: ['gluten_free'] },
  { id: 'prawn-curry', name: 'Prawn Curry', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 170, protein: 16, carbohydrates: 6, fat: 9, fiber: 1, sugar: 2, sodium: 520 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: ['shellfish'], tags: ['gluten_free'] },
  { id: 'paneer-korma', name: 'Paneer Korma', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 290, protein: 12, carbohydrates: 14, fat: 22, fiber: 2, sugar: 4, sodium: 460 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: ['dairy', 'nuts'], tags: ['vegetarian'] },
  { id: 'navratan-korma', name: 'Navratan Korma', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 220, protein: 6, carbohydrates: 18, fat: 15, fiber: 3, sugar: 5, sodium: 420 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: ['dairy', 'nuts'], tags: ['vegetarian'] },
  { id: 'dal-tadka', name: 'Dal Tadka', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 130, protein: 7, carbohydrates: 18, fat: 3, fiber: 4, sugar: 2, sodium: 400 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'dal-palak', name: 'Dal Palak', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 120, protein: 7, carbohydrates: 16, fat: 3, fiber: 4, sugar: 2, sodium: 380 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'kadai-paneer', name: 'Kadai Paneer', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 260, protein: 12, carbohydrates: 12, fat: 19, fiber: 2, sugar: 3, sodium: 460 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'shahi-paneer', name: 'Shahi Paneer', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 270, protein: 12, carbohydrates: 10, fat: 21, fiber: 1, sugar: 4, sodium: 440 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: ['dairy', 'nuts'], tags: ['vegetarian'] },
  { id: 'chicken-korma', name: 'Chicken Korma', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 240, protein: 20, carbohydrates: 8, fat: 15, fiber: 1, sugar: 3, sodium: 500 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: ['dairy', 'nuts'], tags: ['gluten_free'] },
  { id: 'rogan-josh', name: 'Rogan Josh', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 220, protein: 20, carbohydrates: 6, fat: 13, fiber: 1, sugar: 2, sodium: 520 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['gluten_free'] },
  { id: 'vindaloo', name: 'Chicken Vindaloo', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 210, protein: 18, carbohydrates: 8, fat: 12, fiber: 1, sugar: 3, sodium: 580 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['gluten_free'] },
  { id: 'butter-chicken-spicy', name: 'Butter Chicken (Spicy)', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 270, protein: 22, carbohydrates: 9, fat: 17, fiber: 1, sugar: 4, sodium: 560 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: ['dairy'], tags: ['gluten_free'] },

  // Breakfast Items
  { id: 'poha', name: 'Poha (Flattened Rice)', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 140, protein: 3, carbohydrates: 24, fat: 4, fiber: 1.5, sugar: 2, sodium: 320 }, servingSizes: [{ label: '1 plate (150g)', amount: 150, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'upma', name: 'Upma', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 150, protein: 3.5, carbohydrates: 24, fat: 5, fiber: 1.5, sugar: 1, sodium: 340 }, servingSizes: [{ label: '1 bowl (150g)', amount: 150, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'thepla', name: 'Thepla', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 160, protein: 4, carbohydrates: 24, fat: 6, fiber: 2, sugar: 1, sodium: 350 }, servingSizes: [{ label: '2 pieces (80g)', amount: 80, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'misal-pav', name: 'Misal Pav', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 280, protein: 10, carbohydrates: 35, fat: 12, fiber: 6, sugar: 4, sodium: 620 }, servingSizes: [{ label: '1 serving (250g)', amount: 250, unit: 'g' }], allergens: ['gluten'], tags: ['vegetarian'] },
  { id: 'dhokla', name: 'Dhokla', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 120, protein: 5, carbohydrates: 18, fat: 3, fiber: 1, sugar: 2, sodium: 380 }, servingSizes: [{ label: '2 pieces (100g)', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'khandvi', name: 'Khandvi', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 110, protein: 4, carbohydrates: 15, fat: 4, fiber: 1, sugar: 1, sodium: 320 }, servingSizes: [{ label: '1 serving (80g)', amount: 80, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'moong-dal-chilla', name: 'Moong Dal Chilla', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 130, protein: 8, carbohydrates: 16, fat: 3, fiber: 2, sugar: 1, sodium: 340 }, servingSizes: [{ label: '2 pieces (100g)', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'bedmi-puri', name: 'Bedmi Puri', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 180, protein: 5, carbohydrates: 24, fat: 8, fiber: 2, sugar: 1, sodium: 350 }, servingSizes: [{ label: '2 pieces (80g)', amount: 80, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'chole-bhature', name: 'Chole Bhature', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 380, protein: 10, carbohydrates: 48, fat: 18, fiber: 5, sugar: 4, sodium: 650 }, servingSizes: [{ label: '1 serving (250g)', amount: 250, unit: 'g' }], allergens: ['gluten'], tags: ['vegetarian'] },
  { id: 'aloo-puri', name: 'Aloo Puri', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 320, protein: 6, carbohydrates: 42, fat: 15, fiber: 3, sugar: 2, sodium: 520 }, servingSizes: [{ label: '1 serving (200g)', amount: 200, unit: 'g' }], allergens: ['gluten'], tags: ['vegetarian'] },

  // Snacks & Street Food
  { id: 'pani-puri', name: 'Pani Puri', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 150, protein: 2, carbohydrates: 22, fat: 6, fiber: 2, sugar: 2, sodium: 450 }, servingSizes: [{ label: '6 pieces (120g)', amount: 120, unit: 'g' }], allergens: ['gluten'], tags: ['vegetarian'] },
  { id: 'sev-puri', name: 'Sev Puri', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 180, protein: 3, carbohydrates: 24, fat: 8, fiber: 2, sugar: 2, sodium: 480 }, servingSizes: [{ label: '1 plate (120g)', amount: 120, unit: 'g' }], allergens: ['gluten'], tags: ['vegetarian'] },
  { id: 'dahi-puri', name: 'Dahi Puri', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 170, protein: 4, carbohydrates: 22, fat: 7, fiber: 1.5, sugar: 3, sodium: 420 }, servingSizes: [{ label: '6 pieces (120g)', amount: 120, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: ['vegetarian'] },
  { id: 'bhel-puri', name: 'Bhel Puri', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 140, protein: 3, carbohydrates: 22, fat: 5, fiber: 2, sugar: 3, sodium: 420 }, servingSizes: [{ label: '1 plate (100g)', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'dahi-vada', name: 'Dahi Vada', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 180, protein: 6, carbohydrates: 22, fat: 8, fiber: 1.5, sugar: 3, sodium: 400 }, servingSizes: [{ label: '2 pieces (120g)', amount: 120, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'aloo-tikki', name: 'Aloo Tikki', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 160, protein: 3, carbohydrates: 22, fat: 7, fiber: 2, sugar: 2, sodium: 380 }, servingSizes: [{ label: '2 pieces (80g)', amount: 80, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'tandoori-momos', name: 'Tandoori Momos', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 200, protein: 10, carbohydrates: 22, fat: 8, fiber: 1.5, sugar: 2, sodium: 520 }, servingSizes: [{ label: '6 pieces (120g)', amount: 120, unit: 'g' }], allergens: ['gluten'], tags: [] },
  { id: 'momos', name: 'Steamed Momos', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 170, protein: 8, carbohydrates: 22, fat: 5, fiber: 1, sugar: 1, sodium: 480 }, servingSizes: [{ label: '6 pieces (100g)', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: [] },
  { id: 'chana-chaat', name: 'Chana Chaat', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 140, protein: 6, carbohydrates: 18, fat: 5, fiber: 4, sugar: 3, sodium: 420 }, servingSizes: [{ label: '1 plate (150g)', amount: 150, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'papdi-chaat', name: 'Papdi Chaat', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 190, protein: 4, carbohydrates: 25, fat: 8, fiber: 2, sugar: 3, sodium: 480 }, servingSizes: [{ label: '1 plate (120g)', amount: 120, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: ['vegetarian'] },

  // Rice & Breads
  { id: 'jeera-rice', name: 'Jeera Rice', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 180, protein: 3.5, carbohydrates: 32, fat: 4, fiber: 1, sugar: 0.5, sodium: 320 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'peas-pulao', name: 'Peas Pulao', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 175, protein: 4, carbohydrates: 30, fat: 4, fiber: 2, sugar: 1, sodium: 340 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'lemon-rice', name: 'Lemon Rice', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 170, protein: 3, carbohydrates: 28, fat: 5, fiber: 1, sugar: 1, sodium: 350 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'tamarind-rice', name: 'Tamarind Rice', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 185, protein: 3.5, carbohydrates: 30, fat: 6, fiber: 1.5, sugar: 3, sodium: 380 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'coconut-rice', name: 'Coconut Rice', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 195, protein: 3.5, carbohydrates: 28, fat: 8, fiber: 1.5, sugar: 1, sodium: 320 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'tomato-rice', name: 'Tomato Rice', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 175, protein: 3.5, carbohydrates: 29, fat: 5, fiber: 1.5, sugar: 2, sodium: 360 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },

  // Sweets & Desserts
  { id: 'gulab-jamun', name: 'Gulab Jamun', category: 'sweets', cuisines: ['indian'], nutrition: { calories: 175, protein: 2, carbohydrates: 30, fat: 6, fiber: 0.5, sugar: 22, sodium: 120 }, servingSizes: [{ label: '2 pieces (60g)', amount: 60, unit: 'g' }], allergens: ['dairy', 'gluten'], tags: ['vegetarian'] },
  { id: 'rasgulla', name: 'Rasgulla', category: 'sweets', cuisines: ['indian'], nutrition: { calories: 125, protein: 3, carbohydrates: 25, fat: 1.5, fiber: 0, sugar: 20, sodium: 100 }, servingSizes: [{ label: '2 pieces (80g)', amount: 80, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'kheer', name: 'Kheer', category: 'sweets', cuisines: ['indian'], nutrition: { calories: 180, protein: 5, carbohydrates: 28, fat: 6, fiber: 0.5, sugar: 18, sodium: 80 }, servingSizes: [{ label: '1 bowl (150g)', amount: 150, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'halwa', name: 'Moong Dal Halwa', category: 'sweets', cuisines: ['indian'], nutrition: { calories: 250, protein: 6, carbohydrates: 30, fat: 14, fiber: 2, sugar: 18, sodium: 60 }, servingSizes: [{ label: '1 bowl (100g)', amount: 100, unit: 'g' }], allergens: ['dairy', 'nuts'], tags: ['vegetarian'] },
  { id: 'jalebi', name: 'Jalebi', category: 'sweets', cuisines: ['indian'], nutrition: { calories: 220, protein: 2, carbohydrates: 38, fat: 8, fiber: 0.5, sugar: 25, sodium: 80 }, servingSizes: [{ label: '2 pieces (80g)', amount: 80, unit: 'g' }], allergens: ['gluten'], tags: ['vegetarian'] },
  { id: 'barfi', name: 'Kaju Barfi', category: 'sweets', cuisines: ['indian'], nutrition: { calories: 200, protein: 4, carbohydrates: 25, fat: 10, fiber: 0.5, sugar: 18, sodium: 40 }, servingSizes: [{ label: '2 pieces (40g)', amount: 40, unit: 'g' }], allergens: ['dairy', 'nuts'], tags: ['vegetarian'] },
  { id: 'kulfi', name: 'Kulfi', category: 'sweets', cuisines: ['indian'], nutrition: { calories: 190, protein: 5, carbohydrates: 24, fat: 9, fiber: 0.5, sugar: 20, sodium: 60 }, servingSizes: [{ label: '1 piece (70g)', amount: 70, unit: 'g' }], allergens: ['dairy', 'nuts'], tags: ['vegetarian'] },

  // Beverages
  { id: 'masala-chai', name: 'Masala Chai', category: 'beverages', cuisines: ['indian'], nutrition: { calories: 60, protein: 1, carbohydrates: 10, fat: 2, fiber: 0, sugar: 6, sodium: 20 }, servingSizes: [{ label: '1 cup (150ml)', amount: 150, unit: 'ml' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'chai', name: 'Tea (Chai)', category: 'beverages', cuisines: ['indian'], nutrition: { calories: 45, protein: 0.5, carbohydrates: 8, fat: 1.5, fiber: 0, sugar: 5, sodium: 15 }, servingSizes: [{ label: '1 cup (150ml)', amount: 150, unit: 'ml' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'lassi-sweet', name: 'Sweet Lassi', category: 'beverages', cuisines: ['indian'], nutrition: { calories: 120, protein: 4, carbohydrates: 18, fat: 4, fiber: 0, sugar: 16, sodium: 60 }, servingSizes: [{ label: '1 glass (200ml)', amount: 200, unit: 'ml' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'lassi-salt', name: 'Salted Lassi', category: 'beverages', cuisines: ['indian'], nutrition: { calories: 80, protein: 4, carbohydrates: 8, fat: 3, fiber: 0, sugar: 3, sodium: 350 }, servingSizes: [{ label: '1 glass (200ml)', amount: 200, unit: 'ml' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'buttermilk', name: 'Buttermilk (Chaas)', category: 'beverages', cuisines: ['indian'], nutrition: { calories: 40, protein: 2, carbohydrates: 5, fat: 1.5, fiber: 0, sugar: 3, sodium: 300 }, servingSizes: [{ label: '1 glass (200ml)', amount: 200, unit: 'ml' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'jaljeera', name: 'Jaljeera', category: 'beverages', cuisines: ['indian'], nutrition: { calories: 25, protein: 0.5, carbohydrates: 5, fat: 0.5, fiber: 0.5, sugar: 2, sodium: 380 }, servingSizes: [{ label: '1 glass (200ml)', amount: 200, unit: 'ml' }], allergens: [], tags: ['vegan'] },
  { id: 'nannari-sherbet', name: 'Nannari Sherbet', category: 'beverages', cuisines: ['indian'], nutrition: { calories: 80, protein: 0, carbohydrates: 20, fat: 0, fiber: 0, sugar: 18, sodium: 20 }, servingSizes: [{ label: '1 glass (200ml)', amount: 200, unit: 'ml' }], allergens: [], tags: ['vegan'] },

  // Accompaniments
  { id: 'pickle-mango', name: 'Mango Pickle (Achar)', category: 'condiments', cuisines: ['indian'], nutrition: { calories: 45, protein: 0.5, carbohydrates: 5, fat: 3, fiber: 1, sugar: 3, sodium: 680 }, servingSizes: [{ label: '1 tbsp (15g)', amount: 15, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'chutney-mint', name: 'Mint Chutney', category: 'condiments', cuisines: ['indian'], nutrition: { calories: 30, protein: 1, carbohydrates: 5, fat: 1, fiber: 1, sugar: 2, sodium: 320 }, servingSizes: [{ label: '2 tbsp (30g)', amount: 30, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'chutney-coconut', name: 'Coconut Chutney', category: 'condiments', cuisines: ['indian'], nutrition: { calories: 70, protein: 1.5, carbohydrates: 4, fat: 6, fiber: 1, sugar: 1, sodium: 280 }, servingSizes: [{ label: '2 tbsp (30g)', amount: 30, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'raita', name: 'Raita', category: 'condiments', cuisines: ['indian'], nutrition: { calories: 45, protein: 2.5, carbohydrates: 4, fat: 2.5, fiber: 0.5, sugar: 3, sodium: 280 }, servingSizes: [{ label: '1 bowl (100g)', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'papad', name: 'Papad (Papadum)', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 35, protein: 2, carbohydrates: 5, fat: 0.5, fiber: 0.5, sugar: 0, sodium: 280 }, servingSizes: [{ label: '1 piece (10g)', amount: 10, unit: 'g' }], allergens: [], tags: ['vegan'] },
];
