import { FoodItem } from '../../types';

export const indianDishesExtra6: FoodItem[] = [
  // ─── South Indian Kurumas & Kuzhambus ─────────────────────────────────────
  { id: 'aloo-kuruma', name: 'Aloo Kuruma', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 140, protein: 3, carbohydrates: 18, fat: 7, fiber: 3, sugar: 3, sodium: 380 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: ['tree_nuts'], tags: ['vegan'] },
  { id: 'chicken-kuruma', name: 'Chicken Kuruma', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 210, protein: 18, carbohydrates: 8, fat: 13, fiber: 1, sugar: 2, sodium: 480 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: ['tree_nuts'], tags: ['gluten_free'] },
  { id: 'mutton-kuruma', name: 'Mutton Kuruma', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 250, protein: 20, carbohydrates: 8, fat: 16, fiber: 1, sugar: 2, sodium: 500 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: ['tree_nuts'], tags: ['gluten_free'] },
  { id: 'egg-kuruma', name: 'Egg Kuruma', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 170, protein: 10, carbohydrates: 10, fat: 11, fiber: 1, sugar: 2, sodium: 420 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: ['eggs', 'tree_nuts'], tags: ['gluten_free'] },
  { id: 'veg-kuruma', name: 'Vegetable Kuruma', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 120, protein: 3, carbohydrates: 16, fat: 6, fiber: 3, sugar: 3, sodium: 360 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: ['tree_nuts'], tags: ['vegan'] },
  { id: 'paneer-kuruma', name: 'Paneer Kuruma', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 220, protein: 12, carbohydrates: 10, fat: 15, fiber: 1, sugar: 2, sodium: 380 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: ['dairy', 'tree_nuts'], tags: ['vegetarian'] },

  // ─── Kuzhambu & Gravies ──────────────────────────────────────────────────
  { id: 'vatha-kuzhambu', name: 'Vatha Kuzhambu', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 110, protein: 2, carbohydrates: 14, fat: 6, fiber: 2, sugar: 3, sodium: 420 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'puli-kuzhambu', name: 'Puli Kuzhambu', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 90, protein: 2, carbohydrates: 12, fat: 4, fiber: 2, sugar: 3, sodium: 400 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'mor-kuzhambu', name: 'Mor Kuzhambu', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 80, protein: 3, carbohydrates: 8, fat: 4, fiber: 1, sugar: 2, sodium: 350 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'enai-kathirikai', name: 'Enai Kathirikai (Brinjal Curry)', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 130, protein: 2, carbohydrates: 14, fat: 8, fiber: 3, sugar: 3, sodium: 380 }, servingSizes: [{ label: '1 bowl (150g)', amount: 150, unit: 'g' }], allergens: ['peanuts'], tags: ['vegan'] },
  { id: 'gothsu', name: 'Gothsu (Brinjal Mash)', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 90, protein: 2, carbohydrates: 10, fat: 5, fiber: 3, sugar: 2, sodium: 360 }, servingSizes: [{ label: '1 bowl (150g)', amount: 150, unit: 'g' }], allergens: [], tags: ['vegan'] },

  // ─── South Indian Rice Varieties ──────────────────────────────────────────
  { id: 'curd-rice', name: 'Curd Rice', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 140, protein: 4, carbohydrates: 24, fat: 3, fiber: 0.5, sugar: 2, sodium: 120 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'lemon-rice', name: 'Lemon Rice', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 160, protein: 3, carbohydrates: 30, fat: 4, fiber: 1, sugar: 1, sodium: 350 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'tamarind-rice', name: 'Tamarind Rice (Puliyodharai)', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 170, protein: 3, carbohydrates: 30, fat: 5, fiber: 1, sugar: 2, sodium: 380 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'tomato-rice', name: 'Tomato Rice', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 165, protein: 3, carbohydrates: 30, fat: 4, fiber: 1.5, sugar: 3, sodium: 400 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'coconut-rice', name: 'Coconut Rice', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 180, protein: 3, carbohydrates: 28, fat: 7, fiber: 2, sugar: 1, sodium: 320 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: ['tree_nuts'], tags: ['vegan'] },
  { id: 'peas-pulao', name: 'Peas Pulao', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 175, protein: 5, carbohydrates: 30, fat: 4, fiber: 3, sugar: 2, sodium: 360 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'methi-rice', name: 'Methi Rice', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 155, protein: 4, carbohydrates: 28, fat: 3, fiber: 2, sugar: 1, sodium: 340 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'jeera-rice', name: 'Jeera Rice', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 165, protein: 3, carbohydrates: 30, fat: 4, fiber: 0.5, sugar: 0, sodium: 300 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },

  // ─── South Indian Gravies for Rice ────────────────────────────────────────
  { id: 'sambar-rice', name: 'Sambar Rice', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 180, protein: 5, carbohydrates: 32, fat: 4, fiber: 4, sugar: 3, sodium: 420 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'rasam-rice', name: 'Rasam Rice', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 150, protein: 3, carbohydrates: 28, fat: 3, fiber: 1, sugar: 2, sodium: 400 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'dal-rice', name: 'Dal Rice', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 170, protein: 6, carbohydrates: 30, fat: 3, fiber: 3, sugar: 2, sodium: 350 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'avial-rice', name: 'Avial with Rice', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 175, protein: 4, carbohydrates: 28, fat: 6, fiber: 4, sugar: 3, sodium: 380 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }], allergens: ['tree_nuts', 'dairy'], tags: ['vegetarian'] },

  // ─── South Indian Snacks ─────────────────────────────────────────────────
  { id: 'masala-dosa', name: 'Masala Dosa', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 175, protein: 4, carbohydrates: 28, fat: 6, fiber: 2, sugar: 1, sodium: 380 }, servingSizes: [{ label: '1 dosa (120g)', amount: 120, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'rava-dosa', name: 'Rava Dosa', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 160, protein: 3, carbohydrates: 26, fat: 5, fiber: 1, sugar: 0, sodium: 360 }, servingSizes: [{ label: '1 dosa (100g)', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'onion-dosa', name: 'Onion Dosa', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 170, protein: 4, carbohydrates: 28, fat: 5, fiber: 2, sugar: 1, sodium: 370 }, servingSizes: [{ label: '1 dosa (120g)', amount: 120, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'ghee-roast-dosa', name: 'Ghee Roast Dosa', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 190, protein: 4, carbohydrates: 26, fat: 9, fiber: 1, sugar: 0, sodium: 350 }, servingSizes: [{ label: '1 dosa (120g)', amount: 120, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'idli', name: 'Idli', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 70, protein: 2, carbohydrates: 14, fat: 0.5, fiber: 0.5, sugar: 0, sodium: 120 }, servingSizes: [{ label: '2 pieces (80g)', amount: 80, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'medu-vada', name: 'Medu Vada', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 145, protein: 6, carbohydrates: 17, fat: 6, fiber: 2, sugar: 1, sodium: 310 }, servingSizes: [{ label: '2 pieces (80g)', amount: 80, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'uttapam', name: 'Uttapam', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 140, protein: 4, carbohydrates: 22, fat: 4, fiber: 2, sugar: 2, sodium: 350 }, servingSizes: [{ label: '1 uttapam (120g)', amount: 120, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'pongal', name: 'Pongal (Ven Pongal)', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 180, protein: 5, carbohydrates: 26, fat: 7, fiber: 1, sugar: 0, sodium: 320 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'kesari', name: 'Kesari (Rava Kesari)', category: 'sweets', cuisines: ['indian'], nutrition: { calories: 220, protein: 3, carbohydrates: 34, fat: 9, fiber: 0.5, sugar: 22, sodium: 40 }, servingSizes: [{ label: '1 bowl (100g)', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },

  // ─── Tamil Nadu Specialties ──────────────────────────────────────────────
  { id: 'chettinad-chicken', name: 'Chettinad Chicken', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 220, protein: 22, carbohydrates: 6, fat: 13, fiber: 2, sugar: 1, sodium: 520 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['gluten_free'] },
  { id: 'chettinad-egg', name: 'Chettinad Egg Curry', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 180, protein: 10, carbohydrates: 8, fat: 13, fiber: 2, sugar: 2, sodium: 480 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: ['eggs'], tags: ['gluten_free'] },
  { id: 'meen-kuzhambu', name: 'Meen Kuzhambu (Fish Curry)', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 160, protein: 18, carbohydrates: 6, fat: 8, fiber: 1, sugar: 2, sodium: 500 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: ['fish'], tags: ['gluten_free'] },
  { id: 'nandu-soup', name: 'Nandu Soup (Crab Soup)', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 90, protein: 12, carbohydrates: 4, fat: 3, fiber: 0.5, sugar: 1, sodium: 420 }, servingSizes: [{ label: '1 bowl (200ml)', amount: 200, unit: 'ml' }], allergens: ['shellfish'], tags: ['gluten_free'] },
  { id: 'kothu-parotta', name: 'Kothu Parotta', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 280, protein: 14, carbohydrates: 32, fat: 12, fiber: 2, sugar: 2, sodium: 580 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }], allergens: ['gluten', 'eggs'], tags: [] },
  { id: 'biryani-kuska', name: 'Kuska (Plain Biryani)', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 200, protein: 4, carbohydrates: 34, fat: 6, fiber: 1, sugar: 1, sodium: 480 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },

  // ─── Kerala Specialties ──────────────────────────────────────────────────
  { id: 'kerala-fish-curry', name: 'Kerala Fish Curry', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 155, protein: 17, carbohydrates: 6, fat: 8, fiber: 1, sugar: 2, sodium: 480 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: ['fish'], tags: ['gluten_free'] },
  { id: 'kerala-chicken-curry', name: 'Kerala Chicken Curry', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 200, protein: 20, carbohydrates: 6, fat: 12, fiber: 1, sugar: 2, sodium: 500 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['gluten_free'] },
  { id: 'avial', name: 'Avial', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 100, protein: 3, carbohydrates: 10, fat: 6, fiber: 3, sugar: 2, sodium: 360 }, servingSizes: [{ label: '1 bowl (150g)', amount: 150, unit: 'g' }], allergens: ['tree_nuts', 'dairy'], tags: ['vegetarian'] },
  { id: 'olan', name: 'Olan', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 80, protein: 2, carbohydrates: 8, fat: 5, fiber: 2, sugar: 2, sodium: 280 }, servingSizes: [{ label: '1 bowl (150g)', amount: 150, unit: 'g' }], allergens: ['tree_nuts', 'dairy'], tags: ['vegetarian'] },
  { id: 'kalan', name: 'Kalan (Kerala)', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 90, protein: 3, carbohydrates: 10, fat: 5, fiber: 1, sugar: 3, sodium: 320 }, servingSizes: [{ label: '1 bowl (150g)', amount: 150, unit: 'g' }], allergens: ['tree_nuts', 'dairy'], tags: ['vegetarian'] },
  { id: 'thoran', name: 'Thoran (Vegetable Stir-fry)', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 70, protein: 2, carbohydrates: 8, fat: 4, fiber: 3, sugar: 2, sodium: 300 }, servingSizes: [{ label: '1 bowl (100g)', amount: 100, unit: 'g' }], allergens: ['tree_nuts'], tags: ['vegan'] },
  { id: 'kerala-parotta', name: 'Kerala Parotta', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 220, protein: 4, carbohydrates: 34, fat: 8, fiber: 1, sugar: 0, sodium: 360 }, servingSizes: [{ label: '2 pieces (120g)', amount: 120, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'kerala-appam', name: 'Appam', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 120, protein: 2, carbohydrates: 24, fat: 2, fiber: 1, sugar: 2, sodium: 280 }, servingSizes: [{ label: '2 pieces (120g)', amount: 120, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'puttu', name: 'Puttu', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 150, protein: 3, carbohydrates: 30, fat: 2, fiber: 1, sugar: 1, sodium: 280 }, servingSizes: [{ label: '1 cylinder (150g)', amount: 150, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'kerala-sadya', name: 'Kerala Sadya (Full Meal)', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 650, protein: 18, carbohydrates: 100, fat: 22, fiber: 12, sugar: 8, sodium: 800 }, servingSizes: [{ label: '1 full meal', amount: 600, unit: 'g' }], allergens: ['dairy', 'tree_nuts'], tags: ['vegetarian'] },

  // ─── Karnataka Specialties ───────────────────────────────────────────────
  { id: 'bisibele-bath', name: 'Bisibele Bath', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 190, protein: 5, carbohydrates: 30, fat: 7, fiber: 4, sugar: 3, sodium: 420 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'vangi-bath', name: 'Vangi Bath', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 175, protein: 4, carbohydrates: 30, fat: 5, fiber: 3, sugar: 2, sodium: 380 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'kharabath', name: 'Kharabath', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 180, protein: 4, carbohydrates: 30, fat: 6, fiber: 2, sugar: 2, sodium: 400 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'akhki-roti', name: 'Akhki Roti', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 160, protein: 4, carbohydrates: 28, fat: 4, fiber: 3, sugar: 1, sodium: 340 }, servingSizes: [{ label: '2 pieces (120g)', amount: 120, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'ragi-ball', name: 'Ragi Ball (Ragi Mudde)', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 140, protein: 4, carbohydrates: 28, fat: 2, fiber: 3, sugar: 1, sodium: 280 }, servingSizes: [{ label: '1 ball (100g)', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'mutton-chops', name: 'Karnataka Mutton Chops', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 260, protein: 22, carbohydrates: 5, fat: 18, fiber: 1, sugar: 1, sodium: 520 }, servingSizes: [{ label: '1 serving (150g)', amount: 150, unit: 'g' }], allergens: [], tags: ['gluten_free'] },

  // ─── Andhra / Telangana Specialties ──────────────────────────────────────
  { id: 'andhra-chicken-curry', name: 'Andhra Chicken Curry', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 220, protein: 22, carbohydrates: 6, fat: 13, fiber: 2, sugar: 2, sodium: 540 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['gluten_free'] },
  { id: 'gongura-chicken', name: 'Gongura Chicken', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 210, protein: 20, carbohydrates: 8, fat: 12, fiber: 2, sugar: 2, sodium: 520 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['gluten_free'] },
  { id: 'gongura-mutton', name: 'Gongura Mutton', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 250, protein: 22, carbohydrates: 8, fat: 16, fiber: 2, sugar: 2, sodium: 540 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['gluten_free'] },
  { id: 'hyderabadi-dal', name: 'Hyderabadi Khatti Dal', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 110, protein: 6, carbohydrates: 16, fat: 3, fiber: 3, sugar: 3, sodium: 380 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'pesarattu', name: 'Pesarattu', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 150, protein: 8, carbohydrates: 22, fat: 4, fiber: 4, sugar: 1, sodium: 340 }, servingSizes: [{ label: '2 pieces (120g)', amount: 120, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'mla-dosa', name: 'MLA Dosa', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 200, protein: 5, carbohydrates: 28, fat: 8, fiber: 2, sugar: 2, sodium: 400 }, servingSizes: [{ label: '1 dosa (150g)', amount: 150, unit: 'g' }], allergens: ['eggs'], tags: [] },

  // ─── Popular Combos ──────────────────────────────────────────────────────
  { id: 'meals-south', name: 'South Indian Meals (Full)', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 600, protein: 16, carbohydrates: 100, fat: 18, fiber: 10, sugar: 6, sodium: 750 }, servingSizes: [{ label: '1 full meals', amount: 600, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'meals-non-veg', name: 'Non-Veg Meals (Full)', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 750, protein: 35, carbohydrates: 100, fat: 28, fiber: 8, sugar: 6, sodium: 900 }, servingSizes: [{ label: '1 full meals', amount: 700, unit: 'g' }], allergens: ['dairy'], tags: [] },
  { id: 'thali-north', name: 'North Indian Thali', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 700, protein: 25, carbohydrates: 95, fat: 28, fiber: 10, sugar: 8, sodium: 850 }, servingSizes: [{ label: '1 full thali', amount: 650, unit: 'g' }], allergens: ['dairy', 'gluten'], tags: ['vegetarian'] },
  { id: 'mini-meals', name: 'Mini Meals', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 420, protein: 10, carbohydrates: 70, fat: 12, fiber: 6, sugar: 4, sodium: 550 }, servingSizes: [{ label: '1 mini meals', amount: 400, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
];
