import { FoodItem } from '../../types';

export const japaneseDishes: FoodItem[] = [
  { id: 'sushi-roll', name: 'Sushi Roll (California)', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 260, protein: 8, carbohydrates: 38, fat: 8, fiber: 1, sugar: 4, sodium: 680 }, servingSizes: [{ label: '1 roll (8 pieces)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['fish', 'shellfish', 'soy'], tags: [] },
  { id: 'miso-soup', name: 'Miso Soup', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 40, protein: 3, carbohydrates: 5, fat: 1.5, fiber: 1, sugar: 1, sodium: 850 }, servingSizes: [{ label: '1 bowl (250ml)', amount: 250, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['soy'], tags: ['vegan'] },
  { id: 'ramen', name: 'Ramen (Pork)', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 450, protein: 20, carbohydrates: 55, fat: 16, fiber: 3, sugar: 3, sodium: 1200 }, servingSizes: [{ label: '1 bowl (500g)', amount: 500, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'soy', 'eggs'], tags: [] },
  { id: 'udon-soup', name: 'Udon Noodle Soup', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 280, protein: 10, carbohydrates: 45, fat: 5, fiber: 2, sugar: 2, sodium: 980 }, servingSizes: [{ label: '1 bowl (400g)', amount: 400, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'soy'], tags: [] },
  { id: 'teriyaki-chicken', name: 'Teriyaki Chicken', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 220, protein: 25, carbohydrates: 10, fat: 8, fiber: 0.5, sugar: 8, sodium: 680 }, servingSizes: [{ label: '1 serving (150g)', amount: 150, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['soy', 'gluten'], tags: ['gluten_free'] },
  { id: 'tempura', name: 'Vegetable Tempura', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 230, protein: 4, carbohydrates: 22, fat: 14, fiber: 2, sugar: 1, sodium: 380 }, servingSizes: [{ label: '1 serving (120g)', amount: 120, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'eggs'], tags: ['vegan'] },
  { id: 'edamame', name: 'Edamame', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 121, protein: 12, carbohydrates: 9, fat: 5, fiber: 5, sugar: 2, sodium: 5 }, servingSizes: [{ label: '1 cup (155g)', amount: 155, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['soy'], tags: ['vegan', 'gluten_free'] },
  { id: 'japanese-curry', name: 'Japanese Curry Rice', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 280, protein: 10, carbohydrates: 40, fat: 8, fiber: 2, sugar: 5, sodium: 720 }, servingSizes: [{ label: '1 plate (300g)', amount: 300, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: [] },
  { id: 'onigiri', name: 'Onigiri (Rice Ball)', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 180, protein: 3, carbohydrates: 35, fat: 2, fiber: 0.5, sugar: 0, sodium: 380 }, servingSizes: [{ label: '1 piece (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'gyoza', name: 'Gyoza (Pork Dumplings)', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 200, protein: 10, carbohydrates: 20, fat: 8, fiber: 1.5, sugar: 1, sodium: 520 }, servingSizes: [{ label: '6 pieces (120g)', amount: 120, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'soy'], tags: [] },
  { id: 'sashimi', name: 'Salmon Sashimi', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 140, protein: 20, carbohydrates: 0, fat: 7, fiber: 0, sugar: 0, sodium: 44 }, servingSizes: [{ label: '6 slices (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['fish'], tags: ['gluten_free'] },
  { id: 'katsu-curry', name: 'Chicken Katsu Curry', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 380, protein: 22, carbohydrates: 42, fat: 14, fiber: 2, sugar: 4, sodium: 820 }, servingSizes: [{ label: '1 plate (350g)', amount: 350, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'eggs'], tags: [] },
];
