import { FoodItem } from '../../types';

export const koreanDishes: FoodItem[] = [
  { id: 'bibimbap', name: 'Bibimbap', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 350, protein: 15, carbohydrates: 50, fat: 10, fiber: 4, sugar: 5, sodium: 720 }, servingSizes: [{ label: '1 bowl (350g)', amount: 350, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['soy', 'eggs'], tags: [] },
  { id: 'kimchi', name: 'Kimchi', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 23, protein: 1.7, carbohydrates: 4, fat: 0.5, fiber: 1.6, sugar: 2, sodium: 485 }, servingSizes: [{ label: '1 cup (150g)', amount: 150, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['fish'], tags: ['gluten_free'] },
  { id: 'korean-bbq', name: 'Korean BBQ (Bulgogi)', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 280, protein: 25, carbohydrates: 12, fat: 14, fiber: 1, sugar: 8, sodium: 680 }, servingSizes: [{ label: '1 serving (150g)', amount: 150, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['soy', 'sesame'], tags: ['gluten_free'] },
  { id: 'tteokbokki', name: 'Tteokbokki (Spicy Rice Cakes)', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 250, protein: 5, carbohydrates: 45, fat: 5, fiber: 1.5, sugar: 8, sodium: 650 }, servingSizes: [{ label: '1 bowl (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['soy', 'gluten'], tags: ['spicy'] },
  { id: 'japchae', name: 'Japchae (Glass Noodles)', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 180, protein: 4, carbohydrates: 30, fat: 5, fiber: 2, sugar: 3, sodium: 520 }, servingSizes: [{ label: '1 cup (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['soy', 'sesame'], tags: [] },
  { id: 'samgyeopsal', name: 'Samgyeopsal (Grilled Pork Belly)', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 350, protein: 15, carbohydrates: 0, fat: 32, fiber: 0, sugar: 0, sodium: 480 }, servingSizes: [{ label: '1 serving (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['gluten_free'] },
  { id: 'sundubu-jjigae', name: 'Sundubu Jjigae (Soft Tofu Stew)', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 120, protein: 8, carbohydrates: 8, fat: 6, fiber: 2, sugar: 2, sodium: 680 }, servingSizes: [{ label: '1 bowl (300g)', amount: 300, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['soy'], tags: ['spicy'] },
  { id: 'gimbap', name: 'Gimbap (Seaweed Rice Roll)', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 200, protein: 6, carbohydrates: 32, fat: 5, fiber: 2, sugar: 2, sodium: 380 }, servingSizes: [{ label: '1 roll (8 pieces)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: [] },
  { id: 'doenjang-jjigae', name: 'Doenjang Jjigae (Soybean Paste Stew)', category: 'prepared', cuisines: ['korean'], nutrition: { calories: 95, protein: 7, carbohydrates: 8, fat: 4, fiber: 2, sugar: 2, sodium: 750 }, servingSizes: [{ label: '1 bowl (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['soy'], tags: ['vegan'] },
];
