import { FoodItem } from '../../types';

export const legumes: FoodItem[] = [
  { id: 'moong-dal', name: 'Moong Dal (Yellow Lentils)', category: 'legumes', cuisines: ['indian'], nutrition: { calories: 348, protein: 24, carbohydrates: 63, fat: 1.2, fiber: 16, sugar: 7, sodium: 12 }, servingSizes: [{ label: '1 cup cooked (202g)', amount: 202, unit: 'g' }, { label: '100g cooked', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free', 'high_protein'] },
  { id: 'toor-dal', name: 'Toor Dal (Pigeon Peas)', category: 'legumes', cuisines: ['indian'], nutrition: { calories: 343, protein: 22, carbohydrates: 63, fat: 1.5, fiber: 15, sugar: 8, sodium: 13 }, servingSizes: [{ label: '1 cup cooked (200g)', amount: 200, unit: 'g' }, { label: '100g cooked', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free', 'high_protein'] },
  { id: 'masoor-dal', name: 'Masoor Dal (Red Lentils)', category: 'legumes', cuisines: ['indian'], nutrition: { calories: 352, protein: 25, carbohydrates: 60, fat: 1.1, fiber: 11, sugar: 1.8, sodium: 5 }, servingSizes: [{ label: '1 cup cooked (198g)', amount: 198, unit: 'g' }, { label: '100g cooked', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free', 'high_protein'] },
  { id: 'chana-dal', name: 'Chana Dal (Split Chickpeas)', category: 'legumes', cuisines: ['indian'], nutrition: { calories: 336, protein: 21, carbohydrates: 58, fat: 2.5, fiber: 12, sugar: 8, sodium: 17 }, servingSizes: [{ label: '1 cup cooked (196g)', amount: 196, unit: 'g' }, { label: '100g cooked', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free', 'high_protein'] },
  { id: 'chickpeas', name: 'Chickpeas (Garbanzo)', category: 'legumes', cuisines: ['indian', 'mediterranean'], nutrition: { calories: 164, protein: 8.9, carbohydrates: 27, fat: 2.6, fiber: 7.6, sugar: 4.8, sodium: 7 }, servingSizes: [{ label: '1 cup (164g)', amount: 164, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free', 'high_protein'] },
  { id: 'rajma', name: 'Rajma (Kidney Beans)', category: 'legumes', cuisines: ['indian'], nutrition: { calories: 127, protein: 8.7, carbohydrates: 22, fat: 0.5, fiber: 6.4, sugar: 0.3, sodium: 2 }, servingSizes: [{ label: '1 cup (177g)', amount: 177, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free', 'high_protein'] },
  { id: 'black-beans', name: 'Black Beans (cooked)', category: 'legumes', cuisines: ['mexican', 'general'], nutrition: { calories: 132, protein: 8.9, carbohydrates: 24, fat: 0.5, fiber: 8.7, sugar: 0.3, sodium: 1 }, servingSizes: [{ label: '1 cup (172g)', amount: 172, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free', 'high_protein'] },
  { id: 'kidney-beans', name: 'Kidney Beans (cooked)', category: 'legumes', cuisines: ['general'], nutrition: { calories: 127, protein: 8.7, carbohydrates: 22, fat: 0.5, fiber: 6.4, sugar: 0.3, sodium: 2 }, servingSizes: [{ label: '1 cup (177g)', amount: 177, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free', 'high_protein'] },
  { id: 'black-eyed-peas', name: 'Black-Eyed Peas (cooked)', category: 'legumes', cuisines: ['general'], nutrition: { calories: 105, protein: 7, carbohydrates: 19, fat: 0.5, fiber: 5.2, sugar: 3, sodium: 5 }, servingSizes: [{ label: '1 cup (171g)', amount: 171, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'lentils', name: 'Green Lentils (cooked)', category: 'legumes', cuisines: ['general'], nutrition: { calories: 116, protein: 9, carbohydrates: 20, fat: 0.4, fiber: 7.9, sugar: 1.8, sodium: 2 }, servingSizes: [{ label: '1 cup (198g)', amount: 198, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free', 'high_protein'] },
  { id: 'urad-dal', name: 'Urad Dal (Black Gram)', category: 'legumes', cuisines: ['indian'], nutrition: { calories: 341, protein: 25, carbohydrates: 60, fat: 1.4, fiber: 18, sugar: 2.6, sodium: 15 }, servingSizes: [{ label: '1 cup cooked (198g)', amount: 198, unit: 'g' }, { label: '100g cooked', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free', 'high_protein'] },
  { id: 'matar', name: 'Matar (Dried Peas)', category: 'legumes', cuisines: ['indian'], nutrition: { calories: 341, protein: 24, carbohydrates: 60, fat: 1.2, fiber: 25, sugar: 8, sodium: 5 }, servingSizes: [{ label: '1 cup cooked (160g)', amount: 160, unit: 'g' }, { label: '100g cooked', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'navy-beans', name: 'Navy Beans (cooked)', category: 'legumes', cuisines: ['general'], nutrition: { calories: 140, protein: 9, carbohydrates: 25, fat: 0.8, fiber: 9.3, sugar: 0.5, sodium: 1 }, servingSizes: [{ label: '1 cup (182g)', amount: 182, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'pinto-beans', name: 'Pinto Beans (cooked)', category: 'legumes', cuisines: ['mexican'], nutrition: { calories: 143, protein: 9, carbohydrates: 26, fat: 0.7, fiber: 9, sugar: 0.5, sodium: 1 }, servingSizes: [{ label: '1 cup (171g)', amount: 171, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'lima-beans', name: 'Lima Beans (cooked)', category: 'legumes', cuisines: ['general'], nutrition: { calories: 113, protein: 7.8, carbohydrates: 20, fat: 0.4, fiber: 5.8, sugar: 2.9, sodium: 18 }, servingSizes: [{ label: '1 cup (170g)', amount: 170, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'white-beans', name: 'White Beans (Cannellini)', category: 'legumes', cuisines: ['italian', 'general'], nutrition: { calories: 139, protein: 9.7, carbohydrates: 25, fat: 0.7, fiber: 6.3, sugar: 0.4, sodium: 6 }, servingSizes: [{ label: '1 cup (179g)', amount: 179, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'soybeans', name: 'Soybeans (cooked)', category: 'legumes', cuisines: ['general'], nutrition: { calories: 173, protein: 17, carbohydrates: 10, fat: 9, fiber: 6, sugar: 2, sodium: 1 }, servingSizes: [{ label: '1 cup (172g)', amount: 172, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['soy'], tags: ['vegan', 'gluten_free'] },
  { id: 'mung-beans', name: 'Mung Beans (cooked)', category: 'legumes', cuisines: ['indian', 'chinese'], nutrition: { calories: 105, protein: 7, carbohydrates: 19, fat: 0.4, fiber: 7.6, sugar: 2, sodium: 2 }, servingSizes: [{ label: '1 cup (202g)', amount: 202, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'sprouts-moong', name: 'Moong Sprouts', category: 'legumes', cuisines: ['indian'], nutrition: { calories: 30, protein: 3, carbohydrates: 5, fat: 0.1, fiber: 1.8, sugar: 0.4, sodium: 6 }, servingSizes: [{ label: '1 cup (104g)', amount: 104, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
];
