import { FoodItem } from '../../types';

export const mediterraneanDishes: FoodItem[] = [
  { id: 'hummus', name: 'Hummus', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 166, protein: 8, carbohydrates: 14, fat: 10, fiber: 6, sugar: 0, sodium: 367 }, servingSizes: [{ label: '1/2 cup (120g)', amount: 120, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['sesame'], tags: ['vegan'] },
  { id: 'falafel', name: 'Falafel', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 330, protein: 13, carbohydrates: 31, fat: 18, fiber: 5, sugar: 3, sodium: 350 }, servingSizes: [{ label: '4 pieces (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'shawarma', name: 'Chicken Shawarma', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 260, protein: 22, carbohydrates: 15, fat: 13, fiber: 2, sugar: 2, sodium: 580 }, servingSizes: [{ label: '1 wrap (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: [] },
  { id: 'greek-salad', name: 'Greek Salad', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 120, protein: 4, carbohydrates: 6, fat: 9, fiber: 2, sugar: 4, sodium: 420 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian', 'gluten_free'] },
  { id: 'pita-bread', name: 'Pita Bread', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 275, protein: 9, carbohydrates: 55, fat: 1.7, fiber: 2.2, sugar: 1.3, sodium: 502 }, servingSizes: [{ label: '1 pita (60g)', amount: 60, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'baba-ganoush', name: 'Baba Ganoush', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 130, protein: 2, carbohydrates: 8, fat: 10, fiber: 3, sugar: 4, sodium: 320 }, servingSizes: [{ label: '1/2 cup (120g)', amount: 120, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['sesame'], tags: ['vegan'] },
  { id: 'tabbouleh', name: 'Tabbouleh', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 100, protein: 3, carbohydrates: 13, fat: 4, fiber: 3, sugar: 2, sodium: 280 }, servingSizes: [{ label: '1 cup (150g)', amount: 150, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'moussaka', name: 'Moussaka', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 240, protein: 14, carbohydrates: 16, fat: 14, fiber: 3, sugar: 5, sodium: 480 }, servingSizes: [{ label: '1 serving (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy', 'gluten'], tags: [] },
  { id: 'grilled-salmon-med', name: 'Grilled Salmon with Herbs', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 220, protein: 25, carbohydrates: 1, fat: 12, fiber: 0, sugar: 0, sodium: 85 }, servingSizes: [{ label: '1 fillet (170g)', amount: 170, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['fish'], tags: ['gluten_free'] },
];
