import { FoodItem } from '../../types';

export const mexicanDishes: FoodItem[] = [
  { id: 'tacos', name: 'Tacos (Chicken)', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 210, protein: 15, carbohydrates: 18, fat: 9, fiber: 3, sugar: 2, sodium: 480 }, servingSizes: [{ label: '2 tacos (150g)', amount: 150, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: [] },
  { id: 'burrito', name: 'Chicken Burrito', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 380, protein: 25, carbohydrates: 40, fat: 14, fiber: 6, sugar: 3, sodium: 720 }, servingSizes: [{ label: '1 burrito (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: [] },
  { id: 'quesadilla', name: 'Cheese Quesadilla', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 320, protein: 14, carbohydrates: 28, fat: 18, fiber: 2, sugar: 2, sodium: 620 }, servingSizes: [{ label: '1 quesadilla (150g)', amount: 150, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: ['vegetarian'] },
  { id: 'guacamole', name: 'Guacamole', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 150, protein: 2, carbohydrates: 9, fat: 13, fiber: 7, sugar: 1, sodium: 350 }, servingSizes: [{ label: '1/2 cup (120g)', amount: 120, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'nachos', name: 'Nachos with Cheese', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 340, protein: 10, carbohydrates: 30, fat: 22, fiber: 3, sugar: 2, sodium: 680 }, servingSizes: [{ label: '1 plate (150g)', amount: 150, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: ['vegetarian'] },
  { id: 'enchiladas', name: 'Enchiladas (Chicken)', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 280, protein: 18, carbohydrates: 25, fat: 12, fiber: 4, sugar: 3, sodium: 580 }, servingSizes: [{ label: '2 enchiladas (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: [] },
  { id: 'chilaquiles', name: 'Chilaquiles', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 290, protein: 12, carbohydrates: 28, fat: 15, fiber: 3, sugar: 3, sodium: 520 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy', 'eggs'], tags: [] },
  { id: 'elote', name: 'Elote (Street Corn)', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 180, protein: 5, carbohydrates: 22, fat: 9, fiber: 3, sugar: 5, sodium: 350 }, servingSizes: [{ label: '1 ear (150g)', amount: 150, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'fajitas', name: 'Chicken Fajitas', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 250, protein: 20, carbohydrates: 22, fat: 10, fiber: 3, sugar: 3, sodium: 520 }, servingSizes: [{ label: '1 serving (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: [] },
  { id: 'salsa', name: 'Salsa Roja', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 35, protein: 1.5, carbohydrates: 7, fat: 0.3, fiber: 2, sugar: 4, sodium: 420 }, servingSizes: [{ label: '1/4 cup (60g)', amount: 60, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
];
