import { FoodItem } from '../../types';

export const middleEastern: FoodItem[] = [
  { id: 'shawarma-plate', name: 'Chicken Shawarma Plate', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 320, protein: 25, carbohydrates: 30, fat: 12, fiber: 4, sugar: 3, sodium: 620 }, servingSizes: [{ label: '1 plate (300g)', amount: 300, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: [] },
  { id: 'lamb-shawarma', name: 'Lamb Shawarma', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 350, protein: 22, carbohydrates: 30, fat: 16, fiber: 3, sugar: 3, sodium: 580 }, servingSizes: [{ label: '1 wrap (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: [] },
  { id: 'falafel-plate', name: 'Falafel Plate', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 340, protein: 12, carbohydrates: 35, fat: 18, fiber: 8, sugar: 4, sodium: 420 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'sesame'], tags: ['vegan'] },
  { id: 'fattoush', name: 'Fattoush Salad', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 120, protein: 3, carbohydrates: 14, fat: 6, fiber: 3, sugar: 3, sodium: 380 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'sesame'], tags: ['vegan'] },
  { id: 'manakish', name: 'Manakish (Za\'atar)', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 280, protein: 8, carbohydrates: 35, fat: 12, fiber: 3, sugar: 1, sodium: 420 }, servingSizes: [{ label: '1 piece (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'sesame'], tags: ['vegan'] },
  { id: 'sambousek', name: 'Sambousek (Cheese)', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 240, protein: 8, carbohydrates: 22, fat: 14, fiber: 1, sugar: 1, sodium: 380 }, servingSizes: [{ label: '2 pieces (80g)', amount: 80, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: ['vegetarian'] },
  { id: 'kibbeh', name: 'Kibbeh', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 220, protein: 12, carbohydrates: 18, fat: 12, fiber: 2, sugar: 1, sodium: 320 }, servingSizes: [{ label: '1 piece (60g)', amount: 60, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: [] },
  { id: 'batata-harra', name: 'Batata Harra (Spicy Potatoes)', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 180, protein: 3, carbohydrates: 24, fat: 8, fiber: 3, sugar: 2, sodium: 320 }, servingSizes: [{ label: '1 plate (150g)', amount: 150, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'kofta-kebab', name: 'Kofta Kebab', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 240, protein: 20, carbohydrates: 4, fat: 16, fiber: 1, sugar: 2, sodium: 420 }, servingSizes: [{ label: '1 skewer (80g)', amount: 80, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: [] },
  { id: 'adana-kebab', name: 'Adana Kebab', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 260, protein: 22, carbohydrates: 2, fat: 18, fiber: 0.5, sugar: 1, sodium: 380 }, servingSizes: [{ label: '1 serving (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['gluten_free'] },
  { id: 'lahmacun', name: 'Lahmacun (Turkish Pizza)', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 250, protein: 14, carbohydrates: 28, fat: 10, fiber: 2, sugar: 2, sodium: 480 }, servingSizes: [{ label: '1 piece (120g)', amount: 120, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: [] },
  { id: 'pide', name: 'Pide (Turkish Flatbread)', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 280, protein: 14, carbohydrates: 32, fat: 10, fiber: 2, sugar: 2, sodium: 520 }, servingSizes: [{ label: '1 piece (150g)', amount: 150, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: [] },
  { id: 'iskender-kebab', name: 'Iskender Kebab', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 320, protein: 22, carbohydrates: 20, fat: 18, fiber: 2, sugar: 3, sodium: 580 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: [] },
  { id: 'manti', name: 'Manti (Turkish Dumplings)', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 220, protein: 10, carbohydrates: 25, fat: 9, fiber: 2, sugar: 2, sodium: 420 }, servingSizes: [{ label: '1 plate (150g)', amount: 150, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: [] },
  { id: 'turkish-breakfast', name: 'Turkish Breakfast', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 450, protein: 20, carbohydrates: 35, fat: 28, fiber: 4, sugar: 8, sodium: 620 }, servingSizes: [{ label: '1 platter (400g)', amount: 400, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: [] },
  { id: 'mezze-platter', name: 'Mezze Platter', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 380, protein: 12, carbohydrates: 30, fat: 25, fiber: 8, sugar: 4, sodium: 580 }, servingSizes: [{ label: '1 platter (300g)', amount: 300, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['sesame', 'gluten', 'dairy'], tags: ['vegetarian'] },
  { id: 'foul-mudammas', name: 'Foul Mudammas', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 150, protein: 9, carbohydrates: 20, fat: 4, fiber: 6, sugar: 1, sodium: 380 }, servingSizes: [{ label: '1 bowl (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan'] },
];
