import { FoodItem } from '../../types';

export const thaiExtra: FoodItem[] = [
  { id: 'pad-thai-extra', name: 'Pad Thai (Extra)', category: 'prepared', cuisines: ['thai'], nutrition: { calories: 250, protein: 12, carbohydrates: 32, fat: 10, fiber: 2, sugar: 6, sodium: 520 }, servingSizes: [{ label: '1 serving (200g)', amount: 200, unit: 'g' }], allergens: ['peanuts', 'shellfish', 'gluten'], tags: [] },
  { id: 'green-curry', name: 'Green Curry', category: 'prepared', cuisines: ['thai'], nutrition: { calories: 220, protein: 16, carbohydrates: 10, fat: 14, fiber: 2, sugar: 4, sodium: 480 }, servingSizes: [{ label: '1 bowl (250g)', amount: 250, unit: 'g' }], allergens: ['shellfish', 'dairy'], tags: ['spicy'] },
  { id: 'massaman-curry', name: 'Massaman Curry', category: 'prepared', cuisines: ['thai'], nutrition: { calories: 250, protein: 18, carbohydrates: 12, fat: 16, fiber: 2, sugar: 5, sodium: 500 }, servingSizes: [{ label: '1 bowl (250g)', amount: 250, unit: 'g' }], allergens: ['peanuts', 'shellfish'], tags: ['spicy'] },
  { id: 'panang-curry', name: 'Panang Curry', category: 'prepared', cuisines: ['thai'], nutrition: { calories: 240, protein: 16, carbohydrates: 8, fat: 18, fiber: 2, sugar: 4, sodium: 460 }, servingSizes: [{ label: '1 bowl (250g)', amount: 250, unit: 'g' }], allergens: ['peanuts', 'shellfish'], tags: ['spicy'] },
  { id: 'tom-yum-goong', name: 'Tom Yum Goong', category: 'prepared', cuisines: ['thai'], nutrition: { calories: 90, protein: 10, carbohydrates: 6, fat: 3, fiber: 1, sugar: 3, sodium: 520 }, servingSizes: [{ label: '1 bowl (250ml)', amount: 250, unit: 'ml' }], allergens: ['shellfish', 'fish'], tags: ['spicy', 'gluten_free'] },
  { id: 'som-tam', name: 'Som Tam (Green Papaya Salad)', category: 'prepared', cuisines: ['thai'], nutrition: { calories: 100, protein: 3, carbohydrates: 18, fat: 2, fiber: 3, sugar: 10, sodium: 580 }, servingSizes: [{ label: '1 serving (200g)', amount: 200, unit: 'g' }], allergens: ['peanuts', 'shellfish'], tags: ['vegan', 'spicy'] },
  { id: 'thai-fried-rice', name: 'Thai Fried Rice', category: 'prepared', cuisines: ['thai'], nutrition: { calories: 220, protein: 10, carbohydrates: 30, fat: 8, fiber: 2, sugar: 3, sodium: 500 }, servingSizes: [{ label: '1 serving (200g)', amount: 200, unit: 'g' }], allergens: ['soy', 'eggs'], tags: [] },
  { id: 'khao-soi', name: 'Khao Soi', category: 'prepared', cuisines: ['thai'], nutrition: { calories: 300, protein: 18, carbohydrates: 35, fat: 12, fiber: 2, sugar: 5, sodium: 520 }, servingSizes: [{ label: '1 bowl (350g)', amount: 350, unit: 'g' }], allergens: ['gluten', 'eggs'], tags: ['spicy'] },
  { id: 'larb', name: 'Larb (Thai Meat Salad)', category: 'prepared', cuisines: ['thai'], nutrition: { calories: 150, protein: 18, carbohydrates: 4, fat: 8, fiber: 1, sugar: 3, sodium: 420 }, servingSizes: [{ label: '1 serving (150g)', amount: 150, unit: 'g' }], allergens: ['peanuts', 'fish'], tags: ['spicy'] },
  { id: 'pad-see-ew', name: 'Pad See Ew', category: 'prepared', cuisines: ['thai'], nutrition: { calories: 260, protein: 14, carbohydrates: 35, fat: 8, fiber: 2, sugar: 5, sodium: 540 }, servingSizes: [{ label: '1 serving (200g)', amount: 200, unit: 'g' }], allergens: ['gluten', 'soy', 'eggs'], tags: [] },
  { id: 'mango-sticky-rice', name: 'Mango Sticky Rice', category: 'prepared', cuisines: ['thai'], nutrition: { calories: 320, protein: 4, carbohydrates: 68, fat: 4, fiber: 2, sugar: 45, sodium: 30 }, servingSizes: [{ label: '1 serving (200g)', amount: 200, unit: 'g' }], allergens: ['dairy'], tags: [] },
  { id: 'thai-tea', name: 'Thai Iced Tea', category: 'beverages', cuisines: ['thai'], nutrition: { calories: 120, protein: 1, carbohydrates: 22, fat: 3, fiber: 0, sugar: 20, sodium: 20 }, servingSizes: [{ label: '1 glass (300ml)', amount: 300, unit: 'ml' }], allergens: ['dairy'], tags: [] },
];

export const mexicanExtra: FoodItem[] = [
  { id: 'carnitas', name: 'Carnitas', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 260, protein: 24, carbohydrates: 2, fat: 18, fiber: 0, sugar: 1, sodium: 420 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['gluten_free', 'high_protein'] },
  { id: 'al-pastor', name: 'Al Pastor', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 220, protein: 22, carbohydrates: 6, fat: 12, fiber: 2, sugar: 4, sodium: 460 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['gluten_free', 'high_protein'] },
  { id: 'barbacoa', name: 'Barbacoa', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 230, protein: 26, carbohydrates: 2, fat: 14, fiber: 0, sugar: 1, sodium: 400 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['gluten_free', 'high_protein'] },
  { id: 'chile-relleno', name: 'Chile Relleno', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 240, protein: 10, carbohydrates: 16, fat: 16, fiber: 3, sugar: 5, sodium: 380 }, servingSizes: [{ label: '1 piece (150g)', amount: 150, unit: 'g' }], allergens: ['eggs', 'dairy'], tags: [] },
  { id: 'pozole', name: 'Pozole', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 180, protein: 14, carbohydrates: 16, fat: 6, fiber: 3, sugar: 2, sodium: 460 }, servingSizes: [{ label: '1 bowl (250g)', amount: 250, unit: 'g' }], allergens: [], tags: ['gluten_free'] },
  { id: 'tamales', name: 'Tamales', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 250, protein: 8, carbohydrates: 32, fat: 10, fiber: 2, sugar: 3, sodium: 380 }, servingSizes: [{ label: '1 tamale (100g)', amount: 100, unit: 'g' }],   allergens: ['gluten'], tags: [] },
  { id: 'nopales-salad', name: 'Nopales Salad', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 80, protein: 3, carbohydrates: 10, fat: 4, fiber: 4, sugar: 2, sodium: 320 }, servingSizes: [{ label: '1 serving (150g)', amount: 150, unit: 'g' }], allergens: ['dairy'], tags: ['gluten_free'] },
  { id: 'elote', name: 'Elote (Mexican Street Corn)', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 200, protein: 6, carbohydrates: 22, fat: 10, fiber: 3, sugar: 5, sodium: 300 }, servingSizes: [{ label: '1 ear (150g)', amount: 150, unit: 'g' }], allergens: ['dairy'], tags: [] },
  { id: 'chilaquiles', name: 'Chilaquiles', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 280, protein: 12, carbohydrates: 28, fat: 14, fiber: 3, sugar: 4, sodium: 440 }, servingSizes: [{ label: '1 serving (200g)', amount: 200, unit: 'g' }], allergens: ['eggs', 'dairy', 'gluten'], tags: [] },
  { id: 'horchata', name: 'Horchata', category: 'beverages', cuisines: ['mexican'], nutrition: { calories: 110, protein: 1, carbohydrates: 24, fat: 2, fiber: 1, sugar: 20, sodium: 30 }, servingSizes: [{ label: '1 glass (300ml)', amount: 300, unit: 'ml' }], allergens: [], tags: ['vegan'] },
  { id: 'agua-fresca', name: 'Agua Fresca', category: 'beverages', cuisines: ['mexican'], nutrition: { calories: 70, protein: 0, carbohydrates: 18, fat: 0, fiber: 0, sugar: 16, sodium: 10 }, servingSizes: [{ label: '1 glass (300ml)', amount: 300, unit: 'ml' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'tortilla-soup', name: 'Tortilla Soup', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 120, protein: 6, carbohydrates: 14, fat: 5, fiber: 2, sugar: 3, sodium: 480 }, servingSizes: [{ label: '1 bowl (250ml)', amount: 250, unit: 'ml' }], allergens: ['gluten', 'dairy'], tags: [] },
];

export const mediterraneanExtra: FoodItem[] = [
  { id: 'moussaka', name: 'Moussaka', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 250, protein: 14, carbohydrates: 18, fat: 14, fiber: 3, sugar: 5, sodium: 420 }, servingSizes: [{ label: '1 serving (200g)', amount: 200, unit: 'g' }], allergens: ['dairy', 'gluten'], tags: [] },
  { id: 'baklava', name: 'Baklava', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 350, protein: 6, carbohydrates: 38, fat: 22, fiber: 2, sugar: 24, sodium: 120 }, servingSizes: [{ label: '1 piece (60g)', amount: 60, unit: 'g' }], allergens: ['tree_nuts', 'gluten'], tags: [] },
  { id: 'fattoush', name: 'Fattoush Salad', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 120, protein: 3, carbohydrates: 14, fat: 6, fiber: 3, sugar: 4, sodium: 380 }, servingSizes: [{ label: '1 serving (200g)', amount: 200, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'shawarma-plate', name: 'Shawarma Plate', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 300, protein: 22, carbohydrates: 24, fat: 14, fiber: 3, sugar: 3, sodium: 520 }, servingSizes: [{ label: '1 plate (300g)', amount: 300, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: [] },
  { id: 'falafel-plate', name: 'Falafel Plate', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 280, protein: 10, carbohydrates: 32, fat: 14, fiber: 6, sugar: 3, sodium: 460 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }], allergens: ['gluten', 'sesame'], tags: ['vegan'] },
  { id: 'kibbeh', name: 'Kibbeh', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 220, protein: 14, carbohydrates: 18, fat: 10, fiber: 2, sugar: 1, sodium: 380 }, servingSizes: [{ label: '2 pieces (120g)', amount: 120, unit: 'g' }], allergens: ['gluten'], tags: [] },
  { id: 'tabbouleh-extra', name: 'Tabbouleh (Extra)', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 100, protein: 3, carbohydrates: 12, fat: 5, fiber: 4, sugar: 2, sodium: 280 }, servingSizes: [{ label: '1 serving (150g)', amount: 150, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'hummus-extra', name: 'Hummus (Extra)', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 160, protein: 8, carbohydrates: 14, fat: 10, fiber: 4, sugar: 0, sodium: 340 }, servingSizes: [{ label: '1/4 cup (60g)', amount: 60, unit: 'g' }], allergens: ['sesame'], tags: ['vegan', 'gluten_free'] },
  { id: 'baba-ghanoush', name: 'Baba Ghanoush', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 120, protein: 2, carbohydrates: 8, fat: 10, fiber: 3, sugar: 4, sodium: 320 }, servingSizes: [{ label: '1/4 cup (60g)', amount: 60, unit: 'g' }], allergens: ['sesame'], tags: ['vegan', 'gluten_free'] },
  { id: 'gyro', name: 'Gyro', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 280, protein: 18, carbohydrates: 20, fat: 14, fiber: 2, sugar: 3, sodium: 500 }, servingSizes: [{ label: '1 wrap (200g)', amount: 200, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: [] },
  { id: 'souvlaki', name: 'Souvlaki', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 220, protein: 22, carbohydrates: 6, fat: 12, fiber: 1, sugar: 2, sodium: 420 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['gluten_free', 'high_protein'] },
  { id: 'spanakopita', name: 'Spanakopita', category: 'prepared', cuisines: ['mediterranean'], nutrition: { calories: 230, protein: 8, carbohydrates: 18, fat: 14, fiber: 2, sugar: 1, sodium: 380 }, servingSizes: [{ label: '2 pieces (100g)', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy', 'eggs'], tags: [] },
];
