import { FoodItem } from '../../types';

export const soupsStewsExtra: FoodItem[] = [
  { id: 'lentil-soup-2', name: 'Lentil Soup (Extra)', category: 'prepared', cuisines: ['general'], nutrition: { calories: 130, protein: 9, carbohydrates: 18, fat: 3, fiber: 5, sugar: 3, sodium: 440 }, servingSizes: [{ label: '1 bowl (250g)', amount: 250, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'chicken-noodle-soup', name: 'Chicken Noodle Soup', category: 'prepared', cuisines: ['american'], nutrition: { calories: 120, protein: 10, carbohydrates: 12, fat: 4, fiber: 1, sugar: 2, sodium: 480 }, servingSizes: [{ label: '1 bowl (250g)', amount: 250, unit: 'g' }], allergens: ['gluten'], tags: [] },
  { id: 'minestrone', name: 'Minestrone', category: 'prepared', cuisines: ['italian'], nutrition: { calories: 100, protein: 5, carbohydrates: 16, fat: 2, fiber: 4, sugar: 4, sodium: 420 }, servingSizes: [{ label: '1 bowl (250g)', amount: 250, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'french-onion', name: 'French Onion Soup', category: 'prepared', cuisines: ['general'], nutrition: { calories: 160, protein: 8, carbohydrates: 16, fat: 8, fiber: 2, sugar: 5, sodium: 520 }, servingSizes: [{ label: '1 bowl (250g)', amount: 250, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: [] },
  { id: 'clam-chowder', name: 'Clam Chowder', category: 'prepared', cuisines: ['american'], nutrition: { calories: 200, protein: 10, carbohydrates: 18, fat: 10, fiber: 1, sugar: 2, sodium: 580 }, servingSizes: [{ label: '1 bowl (250g)', amount: 250, unit: 'g' }], allergens: ['shellfish', 'dairy', 'gluten'], tags: [] },
  { id: 'tomato-soup', name: 'Tomato Soup', category: 'prepared', cuisines: ['american'], nutrition: { calories: 90, protein: 2, carbohydrates: 16, fat: 3, fiber: 2, sugar: 10, sodium: 440 }, servingSizes: [{ label: '1 bowl (250ml)', amount: 250, unit: 'ml' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'butternut-squash-soup', name: 'Butternut Squash Soup', category: 'prepared', cuisines: ['american'], nutrition: { calories: 100, protein: 2, carbohydrates: 18, fat: 4, fiber: 3, sugar: 6, sodium: 360 }, servingSizes: [{ label: '1 bowl (250ml)', amount: 250, unit: 'ml' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'gazpacho', name: 'Gazpacho', category: 'prepared', cuisines: ['general'], nutrition: { calories: 60, protein: 2, carbohydrates: 10, fat: 2, fiber: 2, sugar: 6, sodium: 440 }, servingSizes: [{ label: '1 bowl (250ml)', amount: 250, unit: 'ml' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'miso-soup-jp', name: 'Miso Soup (Japanese)', category: 'prepared', cuisines: ['japanese'], nutrition: { calories: 40, protein: 3, carbohydrates: 5, fat: 1, fiber: 1, sugar: 1, sodium: 480 }, servingSizes: [{ label: '1 bowl (250ml)', amount: 250, unit: 'ml' }], allergens: ['soy'], tags: ['vegan', 'gluten_free'] },
  { id: 'tom-kha-gai', name: 'Tom Kha Gai', category: 'prepared', cuisines: ['thai'], nutrition: { calories: 140, protein: 10, carbohydrates: 6, fat: 10, fiber: 1, sugar: 3, sodium: 460 }, servingSizes: [{ label: '1 bowl (250ml)', amount: 250, unit: 'ml' }], allergens: ['fish'], tags: ['gluten_free'] },
  { id: 'mulligatawny', name: 'Mulligatawny', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 150, protein: 8, carbohydrates: 18, fat: 6, fiber: 3, sugar: 4, sodium: 480 }, servingSizes: [{ label: '1 bowl (250g)', amount: 250, unit: 'g' }], allergens: ['dairy'], tags: [] },
  { id: 'egg-drop-soup', name: 'Egg Drop Soup', category: 'prepared', cuisines: ['chinese'], nutrition: { calories: 70, protein: 5, carbohydrates: 6, fat: 4, fiber: 0, sugar: 1, sodium: 480 }, servingSizes: [{ label: '1 bowl (250ml)', amount: 250, unit: 'ml' }], allergens: ['eggs', 'soy'], tags: ['gluten_free'] },
  { id: 'wonton-soup-2', name: 'Wonton Soup (Extra)', category: 'prepared', cuisines: ['chinese'], nutrition: { calories: 120, protein: 8, carbohydrates: 14, fat: 4, fiber: 1, sugar: 1, sodium: 520 }, servingSizes: [{ label: '1 bowl (250ml)', amount: 250, unit: 'ml' }], allergens: ['gluten', 'soy'], tags: [] },
  { id: 'beef-stew', name: 'Beef Stew', category: 'prepared', cuisines: ['american'], nutrition: { calories: 220, protein: 20, carbohydrates: 12, fat: 10, fiber: 2, sugar: 3, sodium: 480 }, servingSizes: [{ label: '1 bowl (250g)', amount: 250, unit: 'g' }], allergens: ['gluten'], tags: [] },
  { id: 'chili-con-carne', name: 'Chili con Carne', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 200, protein: 16, carbohydrates: 14, fat: 10, fiber: 4, sugar: 4, sodium: 520 }, servingSizes: [{ label: '1 bowl (250g)', amount: 250, unit: 'g' }], allergens: [], tags: ['gluten_free'] },
];

export const snacksExtra: FoodItem[] = [
  { id: 'protein-bar', name: 'Protein Bar', category: 'snacks', cuisines: ['general'], nutrition: { calories: 220, protein: 20, carbohydrates: 22, fat: 8, fiber: 3, sugar: 8, sodium: 200 }, servingSizes: [{ label: '1 bar (60g)', amount: 60, unit: 'g' }],   allergens: ['nuts', 'soy', 'dairy'], tags: ['high_protein'] },
  { id: 'granola-bar', name: 'Granola Bar', category: 'snacks', cuisines: ['general'], nutrition: { calories: 190, protein: 4, carbohydrates: 32, fat: 7, fiber: 2, sugar: 12, sodium: 120 }, servingSizes: [{ label: '1 bar (40g)', amount: 40, unit: 'g' }], allergens: ['nuts', 'gluten'], tags: [] },
  { id: 'trail-mix', name: 'Trail Mix', category: 'snacks', cuisines: ['general'], nutrition: { calories: 460, protein: 14, carbohydrates: 48, fat: 28, fiber: 5, sugar: 32, sodium: 40 }, servingSizes: [{ label: '1/4 cup (40g)', amount: 40, unit: 'g' }], allergens: ['nuts'], tags: ['vegan'] },
  { id: 'rice-cakes', name: 'Rice Cakes', category: 'snacks', cuisines: ['general'], nutrition: { calories: 35, protein: 1, carbohydrates: 7, fat: 0.3, fiber: 0.4, sugar: 0, sodium: 30 }, servingSizes: [{ label: '1 cake (9g)', amount: 9, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'pretzels', name: 'Pretzels', category: 'snacks', cuisines: ['general'], nutrition: { calories: 380, protein: 10, carbohydrates: 80, fat: 3, fiber: 3, sugar: 3, sodium: 1200 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'dark-chocolate', name: 'Dark Chocolate (70%)', category: 'snacks', cuisines: ['general'], nutrition: { calories: 550, protein: 8, carbohydrates: 46, fat: 36, fiber: 11, sugar: 24, sodium: 20 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }], allergens: ['dairy'], tags: [] },
  { id: 'greek-yogurt', name: 'Greek Yogurt (Plain)', category: 'dairy', cuisines: ['general'], nutrition: { calories: 59, protein: 10, carbohydrates: 4, fat: 1, fiber: 0, sugar: 4, sodium: 36 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian', 'gluten_free'] },
  { id: 'cottage-cheese', name: 'Cottage Cheese', category: 'dairy', cuisines: ['general'], nutrition: { calories: 98, protein: 11, carbohydrates: 3.4, fat: 4.3, fiber: 0, sugar: 3, sodium: 364 }, servingSizes: [{ label: '1/2 cup (113g)', amount: 113, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian', 'gluten_free'] },
  { id: 'jerky-beef', name: 'Beef Jerky', category: 'snacks', cuisines: ['general'], nutrition: { calories: 410, protein: 33, carbohydrates: 16, fat: 26, fiber: 0, sugar: 12, sodium: 1800 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }], allergens: ['soy'], tags: ['gluten_free', 'high_protein'] },
  { id: 'popcorn', name: 'Popcorn (Air-Popped)', category: 'snacks', cuisines: ['general'], nutrition: { calories: 310, protein: 10, carbohydrates: 62, fat: 3.5, fiber: 12, sugar: 0, sodium: 8 }, servingSizes: [{ label: '1 cup (8g)', amount: 8, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'hummus-chips', name: 'Hummus Chips', category: 'snacks', cuisines: ['general'], nutrition: { calories: 450, protein: 8, carbohydrates: 58, fat: 22, fiber: 5, sugar: 2, sodium: 480 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }], allergens: ['gluten', 'sesame'], tags: ['vegan'] },
  { id: 'cheese-puffs', name: 'Cheese Puffs', category: 'snacks', cuisines: ['general'], nutrition: { calories: 500, protein: 6, carbohydrates: 52, fat: 32, fiber: 2, sugar: 4, sodium: 680 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }], allergens: ['dairy', 'gluten'], tags: [] },
  { id: 'beef-jerky', name: 'Teriyaki Beef Jerky', category: 'snacks', cuisines: ['general'], nutrition: { calories: 380, protein: 30, carbohydrates: 20, fat: 22, fiber: 0, sugar: 16, sodium: 1600 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }], allergens: ['soy'], tags: ['gluten_free', 'high_protein'] },
  { id: 'turkey-jerky', name: 'Turkey Jerky', category: 'snacks', cuisines: ['general'], nutrition: { calories: 320, protein: 32, carbohydrates: 18, fat: 14, fiber: 0, sugar: 14, sodium: 1200 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }], allergens: ['soy'], tags: ['gluten_free', 'high_protein'] },
  { id: 'salmon-jerky', name: 'Salmon Jerky', category: 'snacks', cuisines: ['general'], nutrition: { calories: 350, protein: 28, carbohydrates: 15, fat: 20, fiber: 0, sugar: 12, sodium: 900 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }], allergens: ['fish'], tags: ['gluten_free'] },
];
