import { FoodItem } from '../../types';

export const nutsSeeds: FoodItem[] = [
  { id: 'almonds', name: 'Almonds', category: 'nuts_seeds', cuisines: ['general'], nutrition: { calories: 579, protein: 21, carbohydrates: 22, fat: 50, fiber: 12, sugar: 4.4, sodium: 1 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['tree_nuts'], tags: ['vegan', 'gluten_free'] },
  { id: 'walnuts', name: 'Walnuts', category: 'nuts_seeds', cuisines: ['general'], nutrition: { calories: 654, protein: 15, carbohydrates: 14, fat: 65, fiber: 6.7, sugar: 2.6, sodium: 2 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['tree_nuts'], tags: ['vegan', 'gluten_free'] },
  { id: 'cashews', name: 'Cashews', category: 'nuts_seeds', cuisines: ['indian', 'general'], nutrition: { calories: 553, protein: 18, carbohydrates: 30, fat: 44, fiber: 3.3, sugar: 5.9, sodium: 12 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['tree_nuts'], tags: ['vegan', 'gluten_free'] },
  { id: 'peanuts', name: 'Peanuts', category: 'nuts_seeds', cuisines: ['general'], nutrition: { calories: 567, protein: 26, carbohydrates: 16, fat: 49, fiber: 8.5, sugar: 4, sodium: 18 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['peanuts'], tags: ['vegan', 'gluten_free'] },
  { id: 'peanut-butter', name: 'Peanut Butter', category: 'nuts_seeds', cuisines: ['general'], nutrition: { calories: 588, protein: 25, carbohydrates: 20, fat: 50, fiber: 6, sugar: 9, sodium: 459 }, servingSizes: [{ label: '2 tbsp (32g)', amount: 32, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['peanuts'], tags: ['vegan', 'gluten_free'] },
  { id: 'pistachios', name: 'Pistachios', category: 'nuts_seeds', cuisines: ['general'], nutrition: { calories: 560, protein: 20, carbohydrates: 27, fat: 45, fiber: 10.6, sugar: 7.7, sodium: 1 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['tree_nuts'], tags: ['vegan', 'gluten_free'] },
  { id: 'pecans', name: 'Pecans', category: 'nuts_seeds', cuisines: ['general'], nutrition: { calories: 691, protein: 9, carbohydrates: 14, fat: 72, fiber: 9.6, sugar: 4, sodium: 0 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['tree_nuts'], tags: ['vegan', 'gluten_free'] },
  { id: 'hazelnuts', name: 'Hazelnuts', category: 'nuts_seeds', cuisines: ['general'], nutrition: { calories: 628, protein: 15, carbohydrates: 17, fat: 61, fiber: 9.7, sugar: 4.3, sodium: 0 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['tree_nuts'], tags: ['vegan', 'gluten_free'] },
  { id: 'macadamia', name: 'Macadamia Nuts', category: 'nuts_seeds', cuisines: ['general'], nutrition: { calories: 718, protein: 8, carbohydrates: 14, fat: 76, fiber: 8.6, sugar: 4.6, sodium: 5 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['tree_nuts'], tags: ['vegan', 'gluten_free'] },
  { id: 'sunflower-seeds', name: 'Sunflower Seeds', category: 'nuts_seeds', cuisines: ['general'], nutrition: { calories: 584, protein: 21, carbohydrates: 20, fat: 51, fiber: 8.6, sugar: 2.6, sodium: 9 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'pumpkin-seeds', name: 'Pumpkin Seeds', category: 'nuts_seeds', cuisines: ['general'], nutrition: { calories: 559, protein: 30, carbohydrates: 11, fat: 49, fiber: 6, sugar: 1, sodium: 7 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'chia-seeds', name: 'Chia Seeds', category: 'nuts_seeds', cuisines: ['general'], nutrition: { calories: 486, protein: 17, carbohydrates: 42, fat: 31, fiber: 34, sugar: 0, sodium: 16 }, servingSizes: [{ label: '1 tbsp (12g)', amount: 12, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'flaxseeds', name: 'Flaxseeds', category: 'nuts_seeds', cuisines: ['general'], nutrition: { calories: 534, protein: 18, carbohydrates: 29, fat: 42, fiber: 27, sugar: 1.6, sodium: 30 }, servingSizes: [{ label: '1 tbsp (10g)', amount: 10, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'sesame-seeds', name: 'Sesame Seeds', category: 'nuts_seeds', cuisines: ['indian', 'chinese'], nutrition: { calories: 573, protein: 18, carbohydrates: 23, fat: 50, fiber: 12, sugar: 0.3, sodium: 11 }, servingSizes: [{ label: '1 tbsp (9g)', amount: 9, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['sesame'], tags: ['vegan', 'gluten_free'] },
  { id: 'tahini', name: 'Tahini (Sesame Paste)', category: 'nuts_seeds', cuisines: ['mediterranean'], nutrition: { calories: 595, protein: 17, carbohydrates: 21, fat: 54, fiber: 9.3, sugar: 0.5, sodium: 11 }, servingSizes: [{ label: '2 tbsp (30g)', amount: 30, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['sesame'], tags: ['vegan', 'gluten_free'] },
  { id: 'coconut-shreds', name: 'Shredded Coconut', category: 'nuts_seeds', cuisines: ['general'], nutrition: { calories: 660, protein: 6.9, carbohydrates: 24, fat: 65, fiber: 16, sugar: 6, sodium: 37 }, servingSizes: [{ label: '1 cup (80g)', amount: 80, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'pine-nuts', name: 'Pine Nuts', category: 'nuts_seeds', cuisines: ['mediterranean'], nutrition: { calories: 673, protein: 14, carbohydrates: 13, fat: 68, fiber: 3.7, sugar: 3.3, sodium: 2 }, servingSizes: [{ label: '1 oz (28g)', amount: 28, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['tree_nuts'], tags: ['vegan', 'gluten_free'] },
  { id: 'almond-butter', name: 'Almond Butter', category: 'nuts_seeds', cuisines: ['general'], nutrition: { calories: 614, protein: 21, carbohydrates: 19, fat: 56, fiber: 10.5, sugar: 4.2, sodium: 2 }, servingSizes: [{ label: '2 tbsp (32g)', amount: 32, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['tree_nuts'], tags: ['vegan', 'gluten_free'] },
  { id: 'cashew-butter', name: 'Cashew Butter', category: 'nuts_seeds', cuisines: ['general'], nutrition: { calories: 578, protein: 18, carbohydrates: 27, fat: 49, fiber: 5, sugar: 7, sodium: 12 }, servingSizes: [{ label: '2 tbsp (32g)', amount: 32, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['tree_nuts'], tags: ['vegan', 'gluten_free'] },
];
