import { FoodItem } from '../../types';

export const oils: FoodItem[] = [
  { id: 'olive-oil', name: 'Olive Oil', category: 'oils', cuisines: ['mediterranean'], nutrition: { calories: 884, protein: 0, carbohydrates: 0, fat: 100, fiber: 0, sugar: 0, sodium: 2 }, servingSizes: [{ label: '1 tbsp (15ml)', amount: 15, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'coconut-oil', name: 'Coconut Oil', category: 'oils', cuisines: ['general'], nutrition: { calories: 862, protein: 0, carbohydrates: 0, fat: 100, fiber: 0, sugar: 0, sodium: 0 }, servingSizes: [{ label: '1 tbsp (14ml)', amount: 14, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'mustard-oil', name: 'Mustard Oil', category: 'oils', cuisines: ['indian'], nutrition: { calories: 884, protein: 0, carbohydrates: 0, fat: 100, fiber: 0, sugar: 0, sodium: 0 }, servingSizes: [{ label: '1 tbsp (15ml)', amount: 15, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'sesame-oil', name: 'Sesame Oil', category: 'oils', cuisines: ['chinese', 'indian'], nutrition: { calories: 884, protein: 0, carbohydrates: 0, fat: 100, fiber: 0, sugar: 0, sodium: 0 }, servingSizes: [{ label: '1 tbsp (15ml)', amount: 15, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['sesame'], tags: ['vegan', 'gluten_free'] },
  { id: 'sunflower-oil', name: 'Sunflower Oil', category: 'oils', cuisines: ['general'], nutrition: { calories: 884, protein: 0, carbohydrates: 0, fat: 100, fiber: 0, sugar: 0, sodium: 0 }, servingSizes: [{ label: '1 tbsp (15ml)', amount: 15, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'ghee-oil', name: 'Ghee', category: 'oils', cuisines: ['indian'], nutrition: { calories: 900, protein: 0, carbohydrates: 0, fat: 100, fiber: 0, sugar: 0, sodium: 0 }, servingSizes: [{ label: '1 tbsp (15ml)', amount: 15, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['dairy'], tags: ['gluten_free'] },
  { id: 'avocado-oil', name: 'Avocado Oil', category: 'oils', cuisines: ['general'], nutrition: { calories: 884, protein: 0, carbohydrates: 0, fat: 100, fiber: 0, sugar: 0, sodium: 0 }, servingSizes: [{ label: '1 tbsp (15ml)', amount: 15, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'peanut-oil', name: 'Peanut Oil', category: 'oils', cuisines: ['chinese'], nutrition: { calories: 884, protein: 0, carbohydrates: 0, fat: 100, fiber: 0, sugar: 0, sodium: 0 }, servingSizes: [{ label: '1 tbsp (15ml)', amount: 15, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['peanuts'], tags: ['vegan', 'gluten_free'] },
  { id: 'canola-oil', name: 'Canola Oil', category: 'oils', cuisines: ['general'], nutrition: { calories: 884, protein: 0, carbohydrates: 0, fat: 100, fiber: 0, sugar: 0, sodium: 0 }, servingSizes: [{ label: '1 tbsp (15ml)', amount: 15, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'flaxseed-oil', name: 'Flaxseed Oil', category: 'oils', cuisines: ['general'], nutrition: { calories: 884, protein: 0, carbohydrates: 0, fat: 100, fiber: 0, sugar: 0, sodium: 0 }, servingSizes: [{ label: '1 tbsp (15ml)', amount: 15, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'butter-fat', name: 'Butter', category: 'oils', cuisines: ['general'], nutrition: { calories: 717, protein: 0.9, carbohydrates: 0.1, fat: 81, fiber: 0, sugar: 0.1, sodium: 11 }, servingSizes: [{ label: '1 tbsp (14g)', amount: 14, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['gluten_free'] },
];
