import { FoodItem } from '../../types';

export const pizzaPasta: FoodItem[] = [
  { id: 'spaghetti-bolognese', name: 'Spaghetti Bolognese', category: 'prepared', cuisines: ['italian'], nutrition: { calories: 210, protein: 12, carbohydrates: 26, fat: 7, fiber: 2, sugar: 4, sodium: 520 }, servingSizes: [{ label: '1 plate (300g)', amount: 300, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: [] },
  { id: 'spaghetti-carbonara', name: 'Spaghetti Carbonara', category: 'prepared', cuisines: ['italian'], nutrition: { calories: 380, protein: 16, carbohydrates: 38, fat: 18, fiber: 2, sugar: 1, sodium: 620 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy', 'eggs'], tags: [] },
  { id: 'fettuccine-alfredo', name: 'Fettuccine Alfredo', category: 'prepared', cuisines: ['italian'], nutrition: { calories: 400, protein: 12, carbohydrates: 40, fat: 22, fiber: 2, sugar: 2, sodium: 580 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy', 'eggs'], tags: [] },
  { id: 'penne-arrabiata', name: 'Penne Arrabiata', category: 'prepared', cuisines: ['italian'], nutrition: { calories: 200, protein: 6, carbohydrates: 32, fat: 5, fiber: 3, sugar: 5, sodium: 480 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'lasagna', name: 'Lasagna', category: 'prepared', cuisines: ['italian'], nutrition: { calories: 280, protein: 16, carbohydrates: 24, fat: 14, fiber: 2, sugar: 4, sodium: 620 }, servingSizes: [{ label: '1 piece (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy', 'eggs'], tags: [] },
  { id: 'ravioli', name: 'Ravioli (Cheese)', category: 'prepared', cuisines: ['italian'], nutrition: { calories: 250, protein: 12, carbohydrates: 30, fat: 9, fiber: 2, sugar: 2, sodium: 520 }, servingSizes: [{ label: '1 cup (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy', 'eggs'], tags: ['vegetarian'] },
  { id: 'gnocchi', name: 'Gnocchi', category: 'prepared', cuisines: ['italian'], nutrition: { calories: 160, protein: 4, carbohydrates: 32, fat: 2, fiber: 2, sugar: 1, sodium: 380 }, servingSizes: [{ label: '1 cup (150g)', amount: 150, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'eggs'], tags: ['vegetarian'] },
  { id: 'risotto-mushroom', name: 'Risotto (Mushroom)', category: 'prepared', cuisines: ['italian'], nutrition: { calories: 220, protein: 6, carbohydrates: 30, fat: 8, fiber: 1, sugar: 1, sodium: 480 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'risotto-seafood', name: 'Risotto (Seafood)', category: 'prepared', cuisines: ['italian'], nutrition: { calories: 210, protein: 14, carbohydrates: 28, fat: 5, fiber: 1, sugar: 1, sodium: 520 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['shellfish', 'dairy'], tags: [] },
  { id: 'risotto-spinach', name: 'Risotto (Spinach)', category: 'prepared', cuisines: ['italian'], nutrition: { calories: 200, protein: 5, carbohydrates: 30, fat: 7, fiber: 2, sugar: 1, sodium: 460 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'chicken-alfredo', name: 'Chicken Alfredo', category: 'prepared', cuisines: ['italian'], nutrition: { calories: 420, protein: 28, carbohydrates: 38, fat: 18, fiber: 2, sugar: 2, sodium: 620 }, servingSizes: [{ label: '1 plate (280g)', amount: 280, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: ['high_protein'] },
  { id: 'shrimp-scampi', name: 'Shrimp Scampi', category: 'prepared', cuisines: ['italian'], nutrition: { calories: 320, protein: 22, carbohydrates: 30, fat: 12, fiber: 2, sugar: 1, sodium: 580 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['shellfish', 'gluten', 'dairy'], tags: [] },
  { id: 'pesto-pasta', name: 'Pesto Pasta', category: 'prepared', cuisines: ['italian'], nutrition: { calories: 350, protein: 12, carbohydrates: 38, fat: 16, fiber: 2, sugar: 2, sodium: 480 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy', 'nuts'], tags: [] },
  { id: 'baked-ziti', name: 'Baked Ziti', category: 'prepared', cuisines: ['italian'], nutrition: { calories: 320, protein: 16, carbohydrates: 35, fat: 14, fiber: 2, sugar: 3, sodium: 620 }, servingSizes: [{ label: '1 cup (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: [] },
  { id: 'orzo', name: 'Orzo with Vegetables', category: 'prepared', cuisines: ['italian'], nutrition: { calories: 180, protein: 5, carbohydrates: 28, fat: 5, fiber: 2, sugar: 2, sodium: 380 }, servingSizes: [{ label: '1 cup (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'caprese-salad', name: 'Caprese Salad', category: 'prepared', cuisines: ['italian'], nutrition: { calories: 180, protein: 8, carbohydrates: 4, fat: 14, fiber: 1, sugar: 3, sodium: 280 }, servingSizes: [{ label: '1 plate (150g)', amount: 150, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian', 'gluten_free'] },
  { id: 'bruschetta', name: 'Bruschetta', category: 'prepared', cuisines: ['italian'], nutrition: { calories: 160, protein: 4, carbohydrates: 18, fat: 8, fiber: 2, sugar: 2, sodium: 320 }, servingSizes: [{ label: '2 pieces (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'arancini', name: 'Arancini', category: 'prepared', cuisines: ['italian'], nutrition: { calories: 280, protein: 8, carbohydrates: 32, fat: 14, fiber: 1, sugar: 1, sodium: 420 }, servingSizes: [{ label: '2 pieces (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy', 'eggs'], tags: ['vegetarian'] },
  { id: 'calzone', name: 'Calzone', category: 'prepared', cuisines: ['italian'], nutrition: { calories: 320, protein: 16, carbohydrates: 34, fat: 14, fiber: 2, sugar: 3, sodium: 620 }, servingSizes: [{ label: '1 calzone (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten', 'dairy'], tags: [] },
];
