import { FoodItem } from '../../types';

export const proteinFocused: FoodItem[] = [
  { id: 'canned-tuna', name: 'Canned Tuna (in water)', category: 'proteins', cuisines: ['general'], nutrition: { calories: 116, protein: 26, carbohydrates: 0, fat: 0.8, fiber: 0, sugar: 0, sodium: 338 }, servingSizes: [{ label: '1 can (142g)', amount: 142, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['fish'], tags: ['gluten_free', 'high_protein'] },
  { id: 'canned-salmon', name: 'Canned Salmon', category: 'proteins', cuisines: ['general'], nutrition: { calories: 118, protein: 20, carbohydrates: 0, fat: 4, fiber: 0, sugar: 0, sodium: 459 }, servingSizes: [{ label: '1 can (142g)', amount: 142, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['fish'], tags: ['gluten_free', 'high_protein'] },
  { id: 'chicken-liver', name: 'Chicken Liver', category: 'proteins', cuisines: ['general'], nutrition: { calories: 172, protein: 26, carbohydrates: 1, fat: 6.5, fiber: 0, sugar: 0, sodium: 94 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['gluten_free', 'high_protein'] },
  { id: 'beef-liver', name: 'Beef Liver', category: 'proteins', cuisines: ['general'], nutrition: { calories: 175, protein: 27, carbohydrates: 4, fat: 4, fiber: 0, sugar: 0, sodium: 74 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['gluten_free', 'high_protein'] },
  { id: 'turkey-bacon', name: 'Turkey Bacon', category: 'proteins', cuisines: ['american'], nutrition: { calories: 171, protein: 21, carbohydrates: 1, fat: 9, fiber: 0, sugar: 0, sodium: 820 }, servingSizes: [{ label: '2 slices (28g)', amount: 28, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['gluten_free', 'high_protein'] },
  { id: 'chicken-sausage', name: 'Chicken Sausage', category: 'proteins', cuisines: ['general'], nutrition: { calories: 150, protein: 14, carbohydrates: 3, fat: 9, fiber: 0, sugar: 1, sodium: 560 }, servingSizes: [{ label: '1 link (70g)', amount: 70, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['high_protein'] },
  { id: 'pork-sausage', name: 'Pork Sausage', category: 'proteins', cuisines: ['general'], nutrition: { calories: 260, protein: 14, carbohydrates: 2, fat: 22, fiber: 0, sugar: 1, sodium: 580 }, servingSizes: [{ label: '1 link (70g)', amount: 70, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['gluten_free', 'high_protein'] },
  { id: 'lamb-chops', name: 'Lamb Chops', category: 'proteins', cuisines: ['general'], nutrition: { calories: 294, protein: 28, carbohydrates: 0, fat: 20, fiber: 0, sugar: 0, sodium: 72 }, servingSizes: [{ label: '1 chop (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['gluten_free', 'high_protein'] },
  { id: 'veal-cutlet', name: 'Veal Cutlet', category: 'proteins', cuisines: ['italian'], nutrition: { calories: 175, protein: 22, carbohydrates: 0, fat: 9, fiber: 0, sugar: 0, sodium: 80 }, servingSizes: [{ label: '1 cutlet (120g)', amount: 120, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['gluten_free', 'high_protein'] },
  { id: 'bison', name: 'Bison (cooked)', category: 'proteins', cuisines: ['american'], nutrition: { calories: 146, protein: 28, carbohydrates: 0, fat: 3, fiber: 0, sugar: 0, sodium: 66 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['gluten_free', 'high_protein'] },
  { id: 'sea-bass', name: 'Sea Bass (cooked)', category: 'proteins', cuisines: ['general'], nutrition: { calories: 124, protein: 24, carbohydrates: 0, fat: 2.5, fiber: 0, sugar: 0, sodium: 90 }, servingSizes: [{ label: '1 fillet (120g)', amount: 120, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['fish'], tags: ['gluten_free', 'high_protein'] },
  { id: 'halibut', name: 'Halibut (cooked)', category: 'proteins', cuisines: ['general'], nutrition: { calories: 140, protein: 27, carbohydrates: 0, fat: 2.5, fiber: 0, sugar: 0, sodium: 70 }, servingSizes: [{ label: '1 fillet (120g)', amount: 120, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['fish'], tags: ['gluten_free', 'high_protein'] },
  { id: 'octopus', name: 'Octopus (cooked)', category: 'proteins', cuisines: ['general'], nutrition: { calories: 82, protein: 15, carbohydrates: 2, fat: 1, fiber: 0, sugar: 0, sodium: 230 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['shellfish'], tags: ['gluten_free', 'high_protein'] },
  { id: 'squid-calamari', name: 'Squid / Calamari', category: 'proteins', cuisines: ['general'], nutrition: { calories: 92, protein: 15, carbohydrates: 3, fat: 1.5, fiber: 0, sugar: 0, sodium: 200 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['shellfish'], tags: ['gluten_free', 'high_protein'] },
  { id: 'mussels', name: 'Mussels (cooked)', category: 'proteins', cuisines: ['general'], nutrition: { calories: 86, protein: 12, carbohydrates: 4, fat: 2, fiber: 0, sugar: 0, sodium: 250 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['shellfish'], tags: ['gluten_free', 'high_protein'] },
  { id: 'oysters', name: 'Oysters (cooked)', category: 'proteins', cuisines: ['general'], nutrition: { calories: 79, protein: 9, carbohydrates: 4, fat: 2, fiber: 0, sugar: 0, sodium: 225 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['shellfish'], tags: ['gluten_free', 'high_protein'] },
  { id: 'tilapia', name: 'Tilapia (cooked)', category: 'proteins', cuisines: ['general'], nutrition: { calories: 128, protein: 26, carbohydrates: 0, fat: 2.7, fiber: 0, sugar: 0, sodium: 52 }, servingSizes: [{ label: '1 fillet (120g)', amount: 120, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['fish'], tags: ['gluten_free', 'high_protein'] },
  { id: 'smoked-salmon', name: 'Smoked Salmon', category: 'proteins', cuisines: ['general'], nutrition: { calories: 117, protein: 18, carbohydrates: 0, fat: 4, fiber: 0, sugar: 0, sodium: 567 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['fish'], tags: ['gluten_free', 'high_protein'] },
  { id: 'ceviche', name: 'Ceviche', category: 'prepared', cuisines: ['mexican'], nutrition: { calories: 90, protein: 15, carbohydrates: 4, fat: 1, fiber: 1, sugar: 2, sodium: 380 }, servingSizes: [{ label: '1 serving (120g)', amount: 120, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['fish'], tags: ['gluten_free', 'high_protein'] },
  { id: 'jerk-chicken', name: 'Jerk Chicken', category: 'prepared', cuisines: ['general'], nutrition: { calories: 210, protein: 28, carbohydrates: 3, fat: 10, fiber: 1, sugar: 2, sodium: 520 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['gluten_free', 'high_protein'] },
];
