import { FoodItem } from '../../types';

export const southIndian: FoodItem[] = [
  { id: 'mysore-masala-dosa', name: 'Mysore Masala Dosa', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 165, protein: 4, carbohydrates: 24, fat: 6, fiber: 2, sugar: 2, sodium: 400 }, servingSizes: [{ label: '1 dosa (130g)', amount: 130, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'rava-masala-dosa', name: 'Rava Masala Dosa', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 175, protein: 4, carbohydrates: 26, fat: 6, fiber: 2, sugar: 2, sodium: 390 }, servingSizes: [{ label: '1 dosa (120g)', amount: 120, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'onion-rava-dosa', name: 'Onion Rava Dosa', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 180, protein: 4, carbohydrates: 27, fat: 6, fiber: 2, sugar: 2, sodium: 400 }, servingSizes: [{ label: '1 dosa (120g)', amount: 120, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'mysore-pak', name: 'Mysore Pak', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 420, protein: 4, carbohydrates: 48, fat: 24, fiber: 0.5, sugar: 36, sodium: 20 }, servingSizes: [{ label: '1 piece (30g)', amount: 30, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'filter-coffee', name: 'Filter Coffee', category: 'beverages', cuisines: ['indian'], nutrition: { calories: 40, protein: 1, carbohydrates: 6, fat: 1.5, fiber: 0, sugar: 5, sodium: 20 }, servingSizes: [{ label: '1 cup (150ml)', amount: 150, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'kulfi-falooda', name: 'Kulfi Falooda', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 250, protein: 6, carbohydrates: 42, fat: 8, fiber: 1, sugar: 34, sodium: 50 }, servingSizes: [{ label: '1 glass (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy', 'nuts'], tags: ['vegetarian'] },
  { id: 'jigarthanda', name: 'Jigarthanda', category: 'beverages', cuisines: ['indian'], nutrition: { calories: 180, protein: 4, carbohydrates: 32, fat: 5, fiber: 1, sugar: 26, sodium: 40 }, servingSizes: [{ label: '1 glass (250ml)', amount: 250, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'rose-milk', name: 'Rose Milk', category: 'beverages', cuisines: ['indian'], nutrition: { calories: 100, protein: 3, carbohydrates: 16, fat: 3, fiber: 0, sugar: 14, sodium: 40 }, servingSizes: [{ label: '1 glass (200ml)', amount: 200, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'badam-milk', name: 'Badam Milk (Almond)', category: 'beverages', cuisines: ['indian'], nutrition: { calories: 130, protein: 4, carbohydrates: 14, fat: 6, fiber: 1, sugar: 12, sodium: 35 }, servingSizes: [{ label: '1 glass (200ml)', amount: 200, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['dairy', 'nuts'], tags: ['vegetarian'] },
  { id: 'payasam', name: 'Payasam', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 160, protein: 3, carbohydrates: 28, fat: 4, fiber: 0.5, sugar: 20, sodium: 30 }, servingSizes: [{ label: '1 bowl (150g)', amount: 150, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy'], tags: ['vegetarian'] },
  { id: 'semiya-payasam', name: 'Semiya Payasam', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 145, protein: 3, carbohydrates: 24, fat: 4, fiber: 1, sugar: 16, sodium: 30 }, servingSizes: [{ label: '1 bowl (150g)', amount: 150, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['dairy', 'gluten'], tags: ['vegetarian'] },
  { id: 'murukku', name: 'Murukku', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 480, protein: 7, carbohydrates: 55, fat: 26, fiber: 2, sugar: 0.5, sodium: 320 }, servingSizes: [{ label: '1 piece (20g)', amount: 20, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'mixture', name: 'Mixture (South Indian)', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 480, protein: 8, carbohydrates: 52, fat: 28, fiber: 3, sugar: 2, sodium: 380 }, servingSizes: [{ label: '1 cup (50g)', amount: 50, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['peanuts', 'gluten'], tags: ['vegan'] },
  { id: 'thattai', name: 'Thattai', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 460, protein: 7, carbohydrates: 50, fat: 26, fiber: 3, sugar: 1, sodium: 340 }, servingSizes: [{ label: '1 piece (20g)', amount: 20, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'omapodi', name: 'Omapodi', category: 'prepared', cuisines: ['indian'], nutrition: { calories: 470, protein: 8, carbohydrates: 52, fat: 26, fiber: 2, sugar: 1, sodium: 320 }, servingSizes: [{ label: '1 cup (50g)', amount: 50, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
];
