import { FoodItem } from '../../types';

export const thaiDishes: FoodItem[] = [
  { id: 'pad-thai', name: 'Pad Thai', category: 'prepared', cuisines: ['thai'], nutrition: { calories: 290, protein: 12, carbohydrates: 35, fat: 12, fiber: 2, sugar: 6, sodium: 720 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['peanuts', 'shellfish', 'eggs'], tags: [] },
  { id: 'green-curry', name: 'Green Curry (Chicken)', category: 'prepared', cuisines: ['thai'], nutrition: { calories: 220, protein: 18, carbohydrates: 8, fat: 14, fiber: 2, sugar: 3, sodium: 680 }, servingSizes: [{ label: '1 bowl (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['fish'], tags: ['spicy'] },
  { id: 'tom-yum', name: 'Tom Yum Soup', category: 'prepared', cuisines: ['thai'], nutrition: { calories: 80, protein: 8, carbohydrates: 5, fat: 3, fiber: 1, sugar: 2, sodium: 680 }, servingSizes: [{ label: '1 bowl (300g)', amount: 300, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['shellfish'], tags: ['spicy'] },
  { id: 'massaman-curry', name: 'Massaman Curry', category: 'prepared', cuisines: ['thai'], nutrition: { calories: 260, protein: 15, carbohydrates: 18, fat: 15, fiber: 3, sugar: 5, sodium: 620 }, servingSizes: [{ label: '1 bowl (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['peanuts', 'fish'], tags: [] },
  { id: 'mango-sticky-rice', name: 'Mango Sticky Rice', category: 'prepared', cuisines: ['thai'], nutrition: { calories: 300, protein: 3, carbohydrates: 58, fat: 6, fiber: 1, sugar: 30, sodium: 15 }, servingSizes: [{ label: '1 serving (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['gluten_free'] },
  { id: 'thai-fried-rice', name: 'Thai Fried Rice', category: 'prepared', cuisines: ['thai'], nutrition: { calories: 200, protein: 8, carbohydrates: 28, fat: 7, fiber: 1.5, sugar: 3, sodium: 580 }, servingSizes: [{ label: '1 plate (250g)', amount: 250, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['soy', 'fish'], tags: [] },
  { id: 'som-tam', name: 'Som Tam (Papaya Salad)', category: 'prepared', cuisines: ['thai'], nutrition: { calories: 80, protein: 2, carbohydrates: 15, fat: 1.5, fiber: 2.5, sugar: 10, sodium: 580 }, servingSizes: [{ label: '1 plate (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['fish', 'peanuts'], tags: ['spicy'] },
  { id: 'satay', name: 'Chicken Satay', category: 'prepared', cuisines: ['thai'], nutrition: { calories: 200, protein: 18, carbohydrates: 6, fat: 12, fiber: 1, sugar: 3, sodium: 480 }, servingSizes: [{ label: '4 skewers (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['peanuts', 'soy'], tags: ['gluten_free'] },
];
