import { FoodItem } from '../../types';

export const veganProtein: FoodItem[] = [
  { id: 'seitan', name: 'Seitan', category: 'proteins', cuisines: ['general'], nutrition: { calories: 370, protein: 75, carbohydrates: 14, fat: 2, fiber: 1, sugar: 0, sodium: 18 }, servingSizes: [{ label: '100g', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan', 'high_protein'] },
  { id: 'tvp', name: 'Textured Vegetable Protein (TVP)', category: 'legumes', cuisines: ['general'], nutrition: { calories: 335, protein: 52, carbohydrates: 33, fat: 1, fiber: 13, sugar: 0, sodium: 400 }, servingSizes: [{ label: '1/4 cup dry (20g)', amount: 20, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['soy'], tags: ['vegan', 'high_protein'] },
  { id: 'nutritional-yeast', name: 'Nutritional Yeast', category: 'condiments', cuisines: ['general'], nutrition: { calories: 325, protein: 50, carbohydrates: 36, fat: 4, fiber: 26, sugar: 0, sodium: 25 }, servingSizes: [{ label: '2 tbsp (16g)', amount: 16, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'high_protein', 'gluten_free'] },
  { id: 'lentil-patty', name: 'Lentil Patty', category: 'prepared', cuisines: ['general'], nutrition: { calories: 180, protein: 12, carbohydrates: 22, fat: 5, fiber: 6, sugar: 2, sodium: 380 }, servingSizes: [{ label: '1 patty (80g)', amount: 80, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan'] },
  { id: 'black-bean-burger', name: 'Black Bean Burger', category: 'prepared', cuisines: ['american'], nutrition: { calories: 210, protein: 12, carbohydrates: 28, fat: 5, fiber: 8, sugar: 2, sodium: 420 }, servingSizes: [{ label: '1 burger (110g)', amount: 110, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'chickpea-burger', name: 'Chickpea Burger', category: 'prepared', cuisines: ['general'], nutrition: { calories: 190, protein: 10, carbohydrates: 25, fat: 5, fiber: 6, sugar: 2, sodium: 380 }, servingSizes: [{ label: '1 burger (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['gluten'], tags: ['vegan'] },
  { id: 'tofu-scramble', name: 'Tofu Scramble', category: 'prepared', cuisines: ['general'], nutrition: { calories: 140, protein: 12, carbohydrates: 4, fat: 8, fiber: 2, sugar: 1, sodium: 350 }, servingSizes: [{ label: '1 cup (200g)', amount: 200, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: ['soy'], tags: ['vegan'] },
  { id: 'soy-milk', name: 'Soy Milk (unsweetened)', category: 'beverages', cuisines: ['general'], nutrition: { calories: 33, protein: 3, carbohydrates: 1.5, fat: 1.5, fiber: 0.5, sugar: 0, sodium: 45 }, servingSizes: [{ label: '1 cup (240ml)', amount: 240, unit: 'ml' }, { label: '100ml', amount: 100, unit: 'ml' }], allergens: ['soy'], tags: ['vegan', 'gluten_free'] },
  { id: 'pea-protein-powder', name: 'Pea Protein Powder', category: 'beverages', cuisines: ['general'], nutrition: { calories: 400, protein: 80, carbohydrates: 6, fat: 4, fiber: 2, sugar: 1, sodium: 350 }, servingSizes: [{ label: '1 scoop (30g)', amount: 30, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free', 'high_protein'] },
  { id: 'hemp-protein', name: 'Hemp Protein Powder', category: 'beverages', cuisines: ['general'], nutrition: { calories: 360, protein: 50, carbohydrates: 18, fat: 12, fiber: 8, sugar: 1, sodium: 50 }, servingSizes: [{ label: '1 scoop (30g)', amount: 30, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'spirulina', name: 'Spirulina', category: 'beverages', cuisines: ['general'], nutrition: { calories: 290, protein: 57, carbohydrates: 24, fat: 8, fiber: 4, sugar: 3, sodium: 1048 }, servingSizes: [{ label: '1 tbsp (7g)', amount: 7, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
];
