import { FoodItem } from '../../types';

export const vegetablesExotic: FoodItem[] = [
  { id: 'romanesco', name: 'Romanesco', category: 'vegetables', cuisines: ['general'], nutrition: { calories: 30, protein: 3, carbohydrates: 6, fat: 0.4, fiber: 2, sugar: 1, sodium: 15 }, servingSizes: [{ label: '1 cup (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'celery-root', name: 'Celery Root (Celeriac)', category: 'vegetables', cuisines: ['general'], nutrition: { calories: 42, protein: 1.5, carbohydrates: 9, fat: 0.3, fiber: 1.8, sugar: 1.6, sodium: 80 }, servingSizes: [{ label: '1 cup (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'salsify', name: 'Salsify', category: 'vegetables', cuisines: ['general'], nutrition: { calories: 82, protein: 1.8, carbohydrates: 19, fat: 0.3, fiber: 3.3, sugar: 5, sodium: 17 }, servingSizes: [{ label: '1 cup (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'yacon', name: 'Yacón', category: 'vegetables', cuisines: ['general'], nutrition: { calories: 38, protein: 0.6, carbohydrates: 11, fat: 0.1, fiber: 2, sugar: 7, sodium: 4 }, servingSizes: [{ label: '1 cup (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'chayote', name: 'Chayote', category: 'vegetables', cuisines: ['mexican'], nutrition: { calories: 19, protein: 0.8, carbohydrates: 4.5, fat: 0.1, fiber: 1.7, sugar: 1.7, sodium: 2 }, servingSizes: [{ label: '1 cup (132g)', amount: 132, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'malabar-spinach', name: 'Malabar Spinach', category: 'vegetables', cuisines: ['general'], nutrition: { calories: 22, protein: 2.5, carbohydrates: 3.7, fat: 0.4, fiber: 2.1, sugar: 1, sodium: 102 }, servingSizes: [{ label: '1 cup (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'water-spinach', name: 'Water Spinach (Kangkong)', category: 'vegetables', cuisines: ['general'], nutrition: { calories: 19, protein: 2.6, carbohydrates: 3.1, fat: 0.3, fiber: 1.1, sugar: 0.5, sodium: 50 }, servingSizes: [{ label: '1 cup (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'yardlong-beans', name: 'Yardlong Beans', category: 'vegetables', cuisines: ['chinese'], nutrition: { calories: 47, protein: 2.8, carbohydrates: 8, fat: 0.4, fiber: 2.4, sugar: 1.6, sodium: 4 }, servingSizes: [{ label: '1 cup (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'moth-beans', name: 'Moth Beans (Sprouted)', category: 'legumes', cuisines: ['indian'], nutrition: { calories: 120, protein: 9, carbohydrates: 20, fat: 0.8, fiber: 8, sugar: 4, sodium: 10 }, servingSizes: [{ label: '1 cup (150g)', amount: 150, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'hyacinth-beans', name: 'Hyacinth Beans (Val Papdi)', category: 'legumes', cuisines: ['indian'], nutrition: { calories: 58, protein: 4, carbohydrates: 10, fat: 0.3, fiber: 3, sugar: 2, sodium: 8 }, servingSizes: [{ label: '1 cup (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'cluster-beans', name: 'Cluster Beans (Gawar)', category: 'vegetables', cuisines: ['indian'], nutrition: { calories: 45, protein: 3, carbohydrates: 8, fat: 0.2, fiber: 3, sugar: 1, sodium: 10 }, servingSizes: [{ label: '1 cup (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'chrysanthemum-greens', name: 'Chrysanthemum Greens (Shungiku)', category: 'vegetables', cuisines: ['japanese'], nutrition: { calories: 24, protein: 3.3, carbohydrates: 4.6, fat: 0.6, fiber: 3.2, sugar: 0, sodium: 165 }, servingSizes: [{ label: '1 cup (100g)', amount: 100, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'bitter-melon', name: 'Bitter Melon (Karela)', category: 'vegetables', cuisines: ['indian'], nutrition: { calories: 17, protein: 1, carbohydrates: 4, fat: 0.2, fiber: 2, sugar: 1, sodium: 6 }, servingSizes: [{ label: '1 cup (94g)', amount: 94, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
];
