import { FoodItem } from '../../types';

export const wholeSpices: FoodItem[] = [
  { id: 'black-peppercorns', name: 'Black Peppercorns', category: 'condiments', cuisines: ['general'], nutrition: { calories: 251, protein: 10, carbohydrates: 64, fat: 3.3, fiber: 25, sugar: 0.6, sodium: 20 }, servingSizes: [{ label: '1 tsp (2g)', amount: 2, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'cinnamon-stick', name: 'Cinnamon Stick', category: 'condiments', cuisines: ['general'], nutrition: { calories: 247, protein: 4, carbohydrates: 81, fat: 1.2, fiber: 53, sugar: 2, sodium: 10 }, servingSizes: [{ label: '1 stick (5g)', amount: 5, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'cloves', name: 'Cloves', category: 'condiments', cuisines: ['general'], nutrition: { calories: 274, protein: 6, carbohydrates: 66, fat: 13, fiber: 34, sugar: 2.4, sodium: 277 }, servingSizes: [{ label: '1 tsp (2g)', amount: 2, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'cardamom-green', name: 'Cardamom (Green)', category: 'condiments', cuisines: ['indian'], nutrition: { calories: 311, protein: 11, carbohydrates: 68, fat: 6.7, fiber: 28, sugar: 0, sodium: 18 }, servingSizes: [{ label: '1 tsp (2g)', amount: 2, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'cardamom-black', name: 'Cardamom (Black)', category: 'condiments', cuisines: ['indian'], nutrition: { calories: 311, protein: 10.8, carbohydrates: 68.5, fat: 6.7, fiber: 28, sugar: 0, sodium: 18 }, servingSizes: [{ label: '1 tsp (3g)', amount: 3, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'star-anise', name: 'Star Anise', category: 'condiments', cuisines: ['chinese'], nutrition: { calories: 337, protein: 18, carbohydrates: 50, fat: 16, fiber: 15, sugar: 0, sodium: 16 }, servingSizes: [{ label: '1 star (2g)', amount: 2, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'bay-leaf', name: 'Bay Leaf', category: 'condiments', cuisines: ['general'], nutrition: { calories: 313, protein: 8, carbohydrates: 75, fat: 8.4, fiber: 26, sugar: 0, sodium: 23 }, servingSizes: [{ label: '1 leaf (0.5g)', amount: 0.5, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'fenugreek-seeds', name: 'Fenugreek Seeds', category: 'condiments', cuisines: ['indian'], nutrition: { calories: 323, protein: 23, carbohydrates: 58, fat: 6.4, fiber: 25, sugar: 0, sodium: 67 }, servingSizes: [{ label: '1 tsp (3g)', amount: 3, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'mustard-seeds', name: 'Mustard Seeds', category: 'condiments', cuisines: ['indian'], nutrition: { calories: 508, protein: 26, carbohydrates: 28, fat: 36, fiber: 12, sugar: 6, sodium: 13 }, servingSizes: [{ label: '1 tsp (2g)', amount: 2, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'fennel-seeds', name: 'Fennel Seeds', category: 'condiments', cuisines: ['indian'], nutrition: { calories: 345, protein: 16, carbohydrates: 52, fat: 15, fiber: 40, sugar: 0, sodium: 68 }, servingSizes: [{ label: '1 tsp (2g)', amount: 2, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'nutmeg', name: 'Nutmeg', category: 'condiments', cuisines: ['general'], nutrition: { calories: 525, protein: 6, carbohydrates: 49, fat: 36, fiber: 21, sugar: 2.6, sodium: 16 }, servingSizes: [{ label: '1 tsp (2g)', amount: 2, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'mace', name: 'Mace', category: 'condiments', cuisines: ['general'], nutrition: { calories: 475, protein: 7, carbohydrates: 49, fat: 32, fiber: 19, sugar: 0, sodium: 18 }, servingSizes: [{ label: '1 tsp (1.5g)', amount: 1.5, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'asafoetida', name: 'Asafoetida (Hing)', category: 'condiments', cuisines: ['indian'], nutrition: { calories: 297, protein: 4, carbohydrates: 68, fat: 1.1, fiber: 1.5, sugar: 0, sodium: 20 }, servingSizes: [{ label: '1/4 tsp (0.5g)', amount: 0.5, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'carom-seeds', name: 'Carom Seeds (Ajwain)', category: 'condiments', cuisines: ['indian'], nutrition: { calories: 305, protein: 17, carbohydrates: 43, fat: 15, fiber: 39, sugar: 0, sodium: 40 }, servingSizes: [{ label: '1 tsp (2g)', amount: 2, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'dried-red-chilies', name: 'Dried Red Chilies', category: 'condiments', cuisines: ['indian'], nutrition: { calories: 282, protein: 12, carbohydrates: 50, fat: 14, fiber: 15, sugar: 27, sodium: 30 }, servingSizes: [{ label: '1 chili (2g)', amount: 2, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
  { id: 'amchur', name: 'Amchur (Dry Mango Powder)', category: 'condiments', cuisines: ['indian'], nutrition: { calories: 320, protein: 2, carbohydrates: 78, fat: 0.5, fiber: 9, sugar: 55, sodium: 30 }, servingSizes: [{ label: '1 tsp (3g)', amount: 3, unit: 'g' }, { label: '100g', amount: 100, unit: 'g' }], allergens: [], tags: ['vegan', 'gluten_free'] },
];
